DATA = [
    ("SC-01","Khai báo Code phí","Thêm mới Code phí","Happy Path","Thêm mới Code phí thành công (Loại tính phí = Theo giao dịch) → Maker lưu → Checker phê duyệt → Hiển thị trên lưới SPDV",1,"Mục Yêu cầu nghiệp vụ, Flowchart Bước 1-10, US25"),
    ("SC-02","Khai báo Code phí","Thêm mới Code phí","Happy Path","Thêm mới Code phí thành công (Loại tính phí = Định kỳ, Tần suất = Hàng tháng) → Maker lưu → Checker phê duyệt",1,"Mục Yêu cầu nghiệp vụ, Bảng mô tả trường STT Loại tính phí, US25"),
    ("SC-03","Khai báo Code phí","Thêm mới Code phí","Happy Path","Thêm mới Code phí thành công (Loại tính phí = Định kỳ, Tần suất = Hàng năm) → Maker lưu → Checker phê duyệt",1,"Mục Yêu cầu nghiệp vụ, Bảng mô tả trường STT Tần suất, US25"),
    ("SC-04","Khai báo Code phí","Thêm mới Code phí","Happy Path","Thêm mới Code phí với Đối tượng thu phí = Merchant → Maker lưu → Checker phê duyệt",1,"Bảng mô tả trường STT Đối tượng thu phí, US25"),
    ("SC-05","Khai báo Code phí","Thêm mới Code phí","Happy Path","Thêm mới Code phí với tích chọn Phí đã bao gồm VAT và nhập VAT hợp lệ → Maker lưu → Checker phê duyệt",1,"Bảng mô tả trường STT VAT, Phí đã bao gồm VAT, US25"),
    ("SC-06","Khai báo Code phí","Thêm mới Code phí","Happy Path","Thêm mới Code phí không tích Phí đã bao gồm VAT, nhập VAT hợp lệ → Maker lưu → Checker phê duyệt",1,"Mục Yêu cầu nghiệp vụ, đoạn VAT, US25"),
    ("SC-07","Khai báo Code phí","Thêm mới Code phí","Happy Path","Thêm mới Code phí với tích chọn Khai báo theo phân khúc → Maker lưu → Checker phê duyệt",1,"Bảng mô tả trường STT Khai báo theo phân khúc, US25"),
    ("SC-08","Khai báo Code phí","Thông tin chung","Negative","Bỏ trống trường bắt buộc Tên phí khi Xác nhận",1,"Bảng mô tả trường STT Tên phí (★)"),
    ("SC-09","Khai báo Code phí","Thông tin chung","Negative","Bỏ trống trường bắt buộc Loại tiền tệ khi Xác nhận",1,"Bảng mô tả trường STT Loại tiền tệ (★)"),
    ("SC-10","Khai báo Code phí","Thông tin chung","Negative","Bỏ trống trường bắt buộc Đối tượng thu phí khi Xác nhận",1,"Bảng mô tả trường STT Đối tượng thu phí (★)"),
    ("SC-11","Khai báo Code phí","Thông tin chung","Negative","Bỏ trống trường bắt buộc Loại Khách hàng khi Xác nhận",1,"Bảng mô tả trường STT Loại Khách hàng (★)"),
    ("SC-12","Khai báo Code phí","Thông tin chung","Negative","Bỏ trống trường bắt buộc Loại tính phí khi Xác nhận",1,"Bảng mô tả trường STT Loại tính phí (★)"),
    ("SC-13","Khai báo Code phí","Thông tin chung","Negative","Nhập VAT = 0 (vi phạm >0)",1,"Bảng mô tả trường STT VAT, ràng buộc >0 và <=100"),
    ("SC-14","Khai báo Code phí","Thông tin chung","Negative","Nhập VAT = 101 (vi phạm <=100)",1,"Bảng mô tả trường STT VAT, ràng buộc >0 và <=100"),
    ("SC-15","Khai báo Code phí","Thông tin chung","Negative","Nhập VAT = số âm",1,"Bảng mô tả trường STT VAT, ràng buộc số nguyên dương"),
    ("SC-16","Khai báo Code phí","Thông tin chung","Negative","Nhập VAT = số thập phân (VD: 10.5)",1,"Bảng mô tả trường STT VAT, ràng buộc số nguyên dương"),
    ("SC-17","Khai báo Code phí","Thông tin chung","Negative","Tích Phí đã bao gồm VAT nhưng để trống trường VAT",1,"Bảng mô tả trường STT Phí đã bao gồm VAT"),
    ("SC-18","Khai báo Code phí","Thông tin chung","Negative","Loại tính phí = Định kỳ nhưng bỏ trống Tần suất",1,"Bảng mô tả trường STT Tần suất, ràng buộc bắt buộc khi Định kỳ"),
    ("SC-19","Khai báo Code phí","Thông tin chung","Negative","Đối tượng thu phí = Merchant nhưng chọn Loại KH = CBNV",1,"Bảng mô tả trường STT Loại Khách hàng: CBNV không hiển thị khi Merchant"),
    ("SC-20","Khai báo Code phí","Điều kiện tính phí","Negative","Thêm điều kiện trùng bộ (Trường điều kiện + Operator) trong cùng phân vùng",1,"Bảng mô tả trường STT Trường điều kiện, Q04 BA confirmed"),
    ("SC-21","Khai báo Code phí","Điều kiện tính phí","Negative","Bỏ trống Trường điều kiện (★) khi thêm điều kiện",1,"Bảng mô tả trường STT Trường điều kiện (★)"),
    ("SC-22","Khai báo Code phí","Điều kiện tính phí","Negative","Bỏ trống Operator (★) khi thêm điều kiện",1,"Bảng mô tả trường STT Operator (★)"),
    ("SC-23","Khai báo Code phí","Điều kiện tính phí","Negative","Bỏ trống Giá trị (★) khi thêm điều kiện",1,"Bảng mô tả trường STT Giá trị (★)"),
    ("SC-24","Khai báo Code phí","Điều kiện tính phí","Negative","Nhập ký tự đặc biệt không cho phép vào trường Giá trị (VD: @, #, $)",1,"Bảng mô tả trường STT Giá trị, ràng buộc chặn ký tự đặc biệt"),
    ("SC-25","Khai báo Code phí","Điều kiện tính phí","Negative","Nhập Giá trị không đúng kiểu dữ liệu so với Trường điều kiện (VD: nhập text cho trường Number)",1,"Bảng mô tả trường STT Giá trị, ràng buộc kiểu dữ liệu tương đồng"),
    ("SC-26","Khai báo Code phí","Điều kiện tính phí","Negative","Loại tính phí = Định kỳ nhưng khai báo đồng thời điều kiện Tài khoản VÀ Thẻ",1,"Mục Yêu cầu nghiệp vụ, đoạn Điều kiện tính phí Định kỳ"),
    ("SC-27","Khai báo Code phí","Thông tin chung","Boundary","Nhập Tên phí đạt giới hạn tối đa 50 ký tự [QTC-01.6]",1,"QTC-01.6, Bảng mô tả trường STT Tên phí"),
    ("SC-28","Khai báo Code phí","Thông tin chung","Boundary","Nhập Tên phí vượt 51 ký tự [QTC-01.6]",1,"QTC-01.6, Bảng mô tả trường STT Tên phí"),
    ("SC-29","Khai báo Code phí","Thông tin chung","Boundary","Nhập Ghi chú đạt giới hạn tối đa 300 ký tự [QTC-01.6]",1,"QTC-01.6, Bảng mô tả trường STT Ghi chú"),
    ("SC-30","Khai báo Code phí","Thông tin chung","Boundary","Nhập Ghi chú vượt 301 ký tự [QTC-01.6]",1,"QTC-01.6, Bảng mô tả trường STT Ghi chú"),
    ("SC-31","Khai báo Code phí","Thông tin chung","Boundary","Nhập VAT = 1 (biên dưới hợp lệ)",1,"Bảng mô tả trường STT VAT, ràng buộc >0"),
    ("SC-32","Khai báo Code phí","Thông tin chung","Boundary","Nhập VAT = 100 (biên trên hợp lệ)",1,"Bảng mô tả trường STT VAT, ràng buộc <=100"),
    ("SC-33","Khai báo Code phí","Ngày thu","Boundary","Tần suất Hàng tháng: Nhập Ngày thu = 1 (biên dưới)",1,"Bảng mô tả trường STT Ngày thu, 1-31"),
    ("SC-34","Khai báo Code phí","Ngày thu","Boundary","Tần suất Hàng tháng: Nhập Ngày thu = 31 (biên trên)",1,"Bảng mô tả trường STT Ngày thu, 1-31"),
    ("SC-35","Khai báo Code phí","Ngày thu","Boundary","Tần suất Hàng năm: Nhập Ngày thu = 28/02 (biên trên tháng 2)",1,"Bảng mô tả trường STT Ngày thu, Q03 BA: max 28"),
    ("SC-36","Khai báo Code phí","Ngày thu","Boundary","Tần suất Hàng năm: Nhập Ngày thu = 29/02 (vượt biên tháng 2)",1,"Bảng mô tả trường STT Ngày thu, Q03 BA: chỉ đến 28"),
    ("SC-37","Khai báo Code phí","Loại tiền Min/Max","Boundary","Loại tiền = VND: Nhập phí tối thiểu/tối đa = số nguyên dương hợp lệ",1,"Mục Yêu cầu nghiệp vụ, Loại tiền VND/JPY số nguyên"),
    ("SC-38","Khai báo Code phí","Loại tiền Min/Max","Boundary","Loại tiền = VND: Nhập phí tối thiểu/tối đa = số thập phân (không cho phép)",1,"Mục Yêu cầu nghiệp vụ, VND/JPY chỉ số nguyên"),
    ("SC-39","Khai báo Code phí","Loại tiền Min/Max","Boundary","Loại tiền ≠ VND/JPY: Nhập phí tối thiểu/tối đa với 2 số thập phân",1,"Mục Yêu cầu nghiệp vụ, tối đa 2 số sau dấu thập phân"),
    ("SC-40","Khai báo Code phí","Loại tiền Min/Max","Boundary","Loại tiền ≠ VND/JPY: Nhập phí tối thiểu/tối đa với 3 số thập phân (vượt biên)",1,"Mục Yêu cầu nghiệp vụ, tối đa 2 số sau dấu thập phân"),
    ("SC-41","Khai báo Code phí","UI Thông tin chung","UI/UX","Trường Mã phí hiển thị ở trạng thái disable (◎), không cho sửa",1,"Bảng mô tả trường STT Mã phí (◎)"),
    ("SC-42","Khai báo Code phí","UI Thông tin chung","UI/UX","Trường Trạng thái hiển thị mặc định = 'Chờ gán', ở trạng thái disable",1,"Bảng mô tả trường STT Trạng thái (◎)"),
    ("SC-43","Khai báo Code phí","UI Thông tin chung","UI/UX","Chọn Loại tính phí = Định kỳ → Hiển thị Tần suất và Ngày thu",1,"Bảng mô tả trường STT Tần suất, Ngày thu"),
    ("SC-44","Khai báo Code phí","UI Thông tin chung","UI/UX","Chọn Loại tính phí = Theo giao dịch → Ẩn Tần suất và Ngày thu",1,"Bảng mô tả trường STT Tần suất, Ngày thu"),
    ("SC-45","Khai báo Code phí","UI Điều kiện","UI/UX","Loại tính phí = Theo giao dịch → Hiển thị section ĐK Giao dịch + KH + TK",1,"Flowchart Bước 3.a, Bảng mô tả trường STT Loại tính phí"),
    ("SC-46","Khai báo Code phí","UI Điều kiện","UI/UX","Loại tính phí = Định kỳ → Hiển thị section ĐK KH + TK + Thẻ",1,"Flowchart Bước 3.1, Bảng mô tả trường STT Loại tính phí"),
    ("SC-47","Khai báo Code phí","UI Điều kiện","UI/UX","Đối tượng thu phí = Merchant → Dropdown Loại KH ẩn giá trị CBNV",1,"Bảng mô tả trường STT Loại Khách hàng"),
    ("SC-48","Khai báo Code phí","UI Loại tiền","UI/UX","Chọn Loại tiền tệ Code phí trước → Loại tiền Min/Max tự động cập nhật theo",1,"Bảng mô tả trường STT Loại tiền tối thiểu/tối đa, Q02 BA"),
    ("SC-49","Khai báo Code phí","UI Loại tiền","UI/UX","Chọn Loại tiền Min/Max trước, sau đó đổi Loại tiền Code phí → Min/Max KHÔNG tự cập nhật",1,"Bảng mô tả trường STT Loại tiền tối thiểu/tối đa, Q02 BA"),
    ("SC-50","Khai báo Code phí","UI VAT","UI/UX","Bỏ tích Phí đã bao gồm VAT → Trường VAT giữ nguyên giá trị cũ (Q06 BA confirmed)",1,"Bảng mô tả trường VAT, Q06 BA: giữ nguyên giá trị"),
    ("SC-51","Khai báo Code phí","UI Giá trị ĐK","UI/UX","Nhập Giá trị điều kiện → Hệ thống tự động viết hoa và loại bỏ khoảng trắng",1,"Bảng mô tả trường STT Giá trị"),
    ("SC-52","Khai báo Code phí","Nút Đóng","UI/UX","Nhấn nút Đóng → Thoát màn hình, quay về cây SPDV",1,"Flowchart Bước 8.1-8.2, Bảng mô tả Nút Đóng"),
    ("SC-53","Khai báo Code phí","Chỉnh sửa Code phí","Business Logic","Chỉnh sửa Code phí: Chỉ cho phép đổi trạng thái từ Chờ gán → Hủy",1,"Mục Yêu cầu nghiệp vụ, đoạn chỉnh sửa Code phí"),
    ("SC-54","Khai báo Code phí","Chỉnh sửa Code phí","Business Logic","Chỉnh sửa Code phí ở trạng thái Hoạt động → Không cho phép",1,"Mục Yêu cầu nghiệp vụ, chỉ cho phép từ Chờ gán"),
    ("SC-55","Khai báo Code phí","Chỉnh sửa Code phí","Business Logic","Chỉnh sửa Code phí ở trạng thái Ngừng hoạt động → Không cho phép",1,"Mục Yêu cầu nghiệp vụ, chỉ cho phép từ Chờ gán"),
    ("SC-56","Khai báo Code phí","Trạng thái Code phí","Business Logic","Trạng thái mặc định khi thêm mới = Chờ gán (sau khi duyệt)",1,"Mục Yêu cầu nghiệp vụ, Trạng thái mặc định"),
    ("SC-57","Khai báo Code phí","Trạng thái Code phí","Business Logic","Code phí gán Biểu phí Đang/Chưa hiệu lực → Trạng thái = Hoạt động",1,"Mục Yêu cầu nghiệp vụ, đoạn Trạng thái"),
    ("SC-58","Khai báo Code phí","Trạng thái Code phí","Business Logic","Tất cả Biểu phí trực thuộc đều Hết hiệu lực → Trạng thái = Ngừng hoạt động",1,"Mục Yêu cầu nghiệp vụ, đoạn Trạng thái"),
    ("SC-59","Khai báo Code phí","Maker-Checker Thêm mới","Business Logic","Maker Xác nhận thêm mới → Bản ghi Chờ duyệt, hành động = Thêm mới [QTC-12]",1,"Mục Yêu cầu nghiệp vụ, đoạn Maker-Checker"),
    ("SC-60","Khai báo Code phí","Maker-Checker Sửa","Business Logic","Maker Xác nhận sửa (Chờ gán→Hủy) → Bản ghi Chờ duyệt, hành động = Sửa [QTC-12]",1,"Mục Yêu cầu nghiệp vụ, đoạn chỉnh sửa"),
    ("SC-61","Khai báo Code phí","Maker-Checker","Business Logic","Checker phê duyệt → Bản ghi hiển thị trên lưới SPDV chính thức [QTC-12]",1,"Mục Yêu cầu nghiệp vụ, đoạn phê duyệt US25"),
    ("SC-62","Khai báo Code phí","Maker-Checker","Business Logic","Checker từ chối → Maker thấy tại Tác vụ Pending, cho phép Sửa/Xóa [QTC-12]",1,"QTC-12 mục 2"),
    ("SC-63","Khai báo Code phí","Batch Job","Business Logic","Batch Job đầu ngày cập nhật trạng thái Code phí theo Biểu phí (Q07 BA: chưa chốt giờ)",1,"Mục Yêu cầu nghiệp vụ, đoạn Batch Job"),
    ("SC-64","Khai báo Code phí","Loại tính phí Định kỳ","Business Logic","Validation nguồn dữ liệu: ĐK tính phí phải có ≥1 trường cùng nguồn với Công thức",1,"Bảng mô tả trường, phần Điều kiện tính phí Định kỳ"),
    ("SC-65","Khai báo Code phí","Operator logic","Business Logic","Operator IN/NOT IN cho phép nhập nhiều giá trị phân tách bằng dấu phẩy",1,"Bảng mô tả trường STT Giá trị, Operator"),
    ("SC-66","Khai báo Code phí","VAT Logic","Business Logic","Không tích VAT + nhập VAT: Thực thu = Phí + VAT*Phí (công thức tính đúng)",1,"Mục Yêu cầu nghiệp vụ, đoạn VAT"),
    ("SC-67","Khai báo Code phí","VAT Logic","Business Logic","Tích VAT + nhập VAT: Thực thu = Phí hệ thống tính ra (đã bao gồm)",1,"Mục Yêu cầu nghiệp vụ, đoạn VAT"),
    ("SC-68","Khai báo Code phí","Data Integrity","Data Integrity","Code phí gán đúng SPDV cấp cuối, không gán được vào SPDV cấp cha",1,"Mục Yêu cầu nghiệp vụ, đoạn Code phí gán SPDV cấp cuối"),
    ("SC-69","Khai báo Code phí","Data Integrity","Data Integrity","Xóa bản ghi Pending tại Tác vụ Pending → Dữ liệu không ảnh hưởng lưới chính [QTC-12]",1,"QTC-12 mục 2, hành động Xóa"),
    ("SC-70","Khai báo Code phí","Data Integrity","Data Integrity","Mã phí chỉ sinh sau khi Checker cuối cùng phê duyệt [QTC-12 mục 3]",1,"QTC-12 mục 3, Nguyên tắc sinh Mã"),
    ("SC-71","Khai báo Code phí","NFR","NFR","Spam click nút Xác nhận khi Thêm mới Code phí → Chỉ tạo 1 bản ghi",1,"QTC-12, NFR spam click"),
    ("SC-72","Khai báo Code phí","NFR","NFR","Spam click nút Xác nhận khi Chỉnh sửa Code phí → Chỉ tạo 1 bản ghi pending",1,"QTC-12, NFR spam click"),
    ("SC-73","Khai báo Code phí","NFR","NFR","Spam click nút Xóa tại Tác vụ Pending → Chỉ xóa 1 lần",1,"QTC-12, NFR spam click"),
    ("SC-74","Khai báo Code phí","NFR","NFR","Spam click nút Phê duyệt tại Tác vụ chờ duyệt → Chỉ duyệt 1 lần",1,"QTC-12, NFR spam click"),
    ("SC-75","Khai báo Code phí","NFR","NFR","Spam click nút Từ chối tại Tác vụ chờ duyệt → Chỉ từ chối 1 lần",1,"QTC-12, NFR spam click"),
]
HEADERS = ["Mã Kịch Bản (ID)","Feature","Module","Loại Test Case","Tên Test Case / Kịch bản","SL TC dự kiến","Trích dẫn tài liệu (Traceability)"]
