"""US05 Part C - Test Case Coverage Data"""

FEATURE = "US05 - Thiết lập Quy tắc tính phí"

SCENARIOS = [
    # === HAPPY PATH ===
    ("SC-01", FEATURE, "Quy tắc tính phí", "Happy Path",
     "Thêm mới quy tắc tính phí KHÔNG theo nhóm KH — nhập Công thức, Tối thiểu, Tối đa hợp lệ",
     1, "Mục YCNV: 'Khi người dùng không lựa chọn Khai báo theo nhóm KH... chỉ được khai báo 1 Công thức'"),
    ("SC-02", FEATURE, "Quy tắc tính phí", "Happy Path",
     "Thêm mới quy tắc tính phí THEO nhóm KH — chọn Nhóm KH, nhập Công thức, Tối thiểu, Tối đa hợp lệ",
     1, "Mục YCNV: 'Khi người dùng lựa chọn Khai báo theo nhóm KH... khai báo nhiều Công thức'"),
    ("SC-03", FEATURE, "Quy tắc tính phí", "Happy Path",
     "Thêm nhiều nhóm KH với công thức khác nhau — mỗi nhóm có Tối thiểu/Tối đa riêng",
     1, "Mục YCNV: 'mỗi công thức áp dụng riêng cho mỗi nhóm KH'"),
    ("SC-04", FEATURE, "Thiết lập công thức", "Happy Path",
     "Mở màn hình Thiết lập công thức — chọn Biến từ danh sách bên trái, Biến hiển thị dạng #Field# tại vị trí con trỏ",
     1, "Bảng mô tả trường: 'Click vào trường giá trị tính phí... hiển thị dưới định dạng #Field#'"),
    ("SC-05", FEATURE, "Thiết lập công thức", "Happy Path",
     "Nhập công thức hợp lệ sử dụng Biến + toán tử + hàm (VD: #Amount# * 0.01) và Xác nhận thành công",
     1, "Mục YCNV: 'Công thức tính phí là công thức toán học'"),
    ("SC-06", FEATURE, "Thiết lập công thức", "Happy Path",
     "Nhập công thức sử dụng hàm ROUND/ROUNDUP/ROUNDDOWN hợp lệ và Xác nhận thành công",
     1, "Mục YCNV: Danh sách hàm được phép: ROUND, ROUNDUP, ROUNDDOWN"),
    ("SC-07", FEATURE, "Thiết lập công thức", "Happy Path",
     "Nhập công thức sử dụng hàm DATE_DIFF với 2 tham số ngày hợp lệ và Xác nhận thành công",
     1, "Mục YCNV: 'DATE_DIFF: Hàm tính số ngày giữa 2 ngày'"),
    ("SC-08", FEATURE, "Thiết lập công thức", "Happy Path",
     "Nhập công thức sử dụng hàm MONTHS_BETWEEN với 2 tham số ngày hợp lệ và Xác nhận",
     1, "Mục YCNV: 'MONTHS_BETWEEN: Hàm tính số tháng giữa 2 ngày'"),
    ("SC-09", FEATURE, "Thiết lập công thức", "Happy Path",
     "Nhập công thức sử dụng hàm MIN/MAX lồng nhau hợp lệ (VD: MAX(MIN(#A#,#B#),#C#)) và Xác nhận",
     1, "Mục YCNV: 'Hàm MIN, MAX được lồng nhau'"),
    ("SC-10", FEATURE, "Thiết lập công thức", "Happy Path",
     "Nhập tên Biến thủ công đúng định dạng #Field# — hệ thống gợi ý gần đúng và chấp nhận",
     1, "Bảng mô tả trường: 'người dùng có thể nhập tên trường theo định dạng #Field#... hiển thị gợi ý gần đúng'"),
    ("SC-11", FEATURE, "Thiết lập công thức", "Happy Path",
     "Tìm kiếm nhanh Biến trong danh sách Trường giá trị tính phí — kết quả lọc đúng",
     1, "Bảng mô tả trường: 'Người dùng có thể tìm kiếm nhanh theo mã/tên trường giá trị tính phí'; BA Q3 confirm"),
    ("SC-12", FEATURE, "Thiết lập công thức", "Happy Path",
     "Nhấn Đóng tại màn hình Thiết lập công thức — quay về màn hình Khai báo Code phí, công thức không lưu",
     1, "Bảng diễn giải lưu đồ: Bước 9.1 Đóng → 9.2 Hiển thị màn hình Khai báo code phí"),
    ("SC-13", FEATURE, "Quy tắc tính phí", "Happy Path",
     "Khai báo Loại tiền tệ Tối thiểu/Tối đa KHÁC Loại tiền tệ Code phí khi công thức là biến động",
     1, "Mục YCNV: 'Loại tiền tệ của Số tiền phí tối thiểu, tối đa có thể khác với Loại tiền tệ của Code phí'"),
    ("SC-14", FEATURE, "Quy tắc tính phí", "Happy Path",
     "Danh sách Trường giá trị tính phí hiển thị đúng theo Loại tính phí: Theo giao dịch → Nguồn = API",
     1, "Bảng mô tả trường: 'Loại tính phí = Theo giao dịch → Nguồn dữ liệu = API'"),
    ("SC-15", FEATURE, "Quy tắc tính phí", "Happy Path",
     "Danh sách Trường giá trị tính phí hiển thị đúng theo Loại tính phí: Định kỳ → Nguồn = ETL",
     1, "Bảng mô tả trường: 'Loại tính phí = Định kỳ → Nguồn dữ liệu = ETL'"),

    # === NEGATIVE PATH ===
    ("SC-16", FEATURE, "Thiết lập công thức", "Negative Path",
     "Xác nhận công thức rỗng (không nhập gì) — hệ thống báo lỗi không cho lưu",
     1, "Bảng mô tả trường: Công thức (★ bắt buộc)"),
    ("SC-17", FEATURE, "Thiết lập công thức", "Negative Path",
     "Nhập công thức chỉ gồm 2 giá trị số học cụ thể (VD: 50000 + 10000) — báo lỗi không cho lưu",
     1, "Mục YCNV: 'Khi công thức nhập 2 hoặc nhiều cấu phần... có 2 cấu là các giá trị số học... báo lỗi'"),
    ("SC-18", FEATURE, "Thiết lập công thức", "Negative Path",
     "Nhập Biến không thuộc danh sách hệ thống (VD: #INVALID_VAR#) — báo lỗi Biến không hợp lệ",
     1, "Mục YCNV: 'hệ thống sẽ kiểm tra Biến... nếu không thì báo lỗi Biến không hợp lệ'"),
    ("SC-19", FEATURE, "Thiết lập công thức", "Negative Path",
     "Nhập hàm DATE_DIFF/MONTHS_BETWEEN thiếu dấu ngoặc () — báo lỗi cú pháp",
     1, "Mục YCNV: 'Các hàm... bắt buộc phải đi kèm ký tự ( và ký tự )'"),
    ("SC-20", FEATURE, "Thiết lập công thức", "Negative Path",
     "Nhập hàm DATE_DIFF chỉ có 1 tham số (VD: DATE_DIFF(#D1#)) — báo lỗi",
     1, "Mục YCNV: 'Hàm MONTHS_BETWEEN, DATE_DIFF bắt buộc phải nhập 2 tham số'"),
    ("SC-21", FEATURE, "Thiết lập công thức", "Negative Path",
     "Nhập hàm MONTHS_BETWEEN lồng DATE_DIFF (VD: MONTHS_BETWEEN(DATE_DIFF(...),#D#)) — báo lỗi",
     1, "Mục YCNV: 'Hàm MONTHS_BETWEEN không được lồng với các hàm DATE_DIFF/MIN/MAX'"),
    ("SC-22", FEATURE, "Thiết lập công thức", "Negative Path",
     "Nhập hàm DATE_DIFF lồng MONTHS_BETWEEN — báo lỗi",
     1, "Mục YCNV: 'Hàm DATE_DIFF không được lồng với các hàm MONTHS_BETWEEN/MIN/MAX'"),
    ("SC-23", FEATURE, "Thiết lập công thức", "Negative Path",
     "Nhập hàm MIN/MAX lồng DATE_DIFF (VD: MIN(DATE_DIFF(#D1#,#D2#),30)) — báo lỗi",
     1, "Mục YCNV: 'MIN, MAX... không được lồng với MONTHS_BETWEEN/DATE_DIFF'; BA Q4 confirm"),
    ("SC-24", FEATURE, "Thiết lập công thức", "Negative Path",
     "Nhập ký tự không hợp lệ trong công thức (VD: chữ cái a-z, ký tự đặc biệt @!$%) — hệ thống không cho nhập hoặc báo lỗi",
     1, "Bảng mô tả trường: 'Hệ thống hiển thị và chỉ cho phép nhập: Các giá trị là số học, toán tử...'"),
    ("SC-25", FEATURE, "Quy tắc tính phí", "Negative Path",
     "Công thức là giá trị số học cụ thể + Loại tiền tệ Code phí KHÁC Loại tiền Tối thiểu/Tối đa — báo lỗi",
     1, "Bảng mô tả trường: 'Khi công thức là 1 giá trị số học cụ thể... Loại tiền tệ khác... báo lỗi'"),
    ("SC-26", FEATURE, "Quy tắc tính phí", "Negative Path",
     "Bỏ trống trường Tối thiểu khi Xác nhận khai báo Code phí — FE chặn, báo trường bắt buộc",
     1, "Bảng mô tả trường: Tối thiểu (★ bắt buộc)"),
    ("SC-27", FEATURE, "Quy tắc tính phí", "Negative Path",
     "Bỏ trống trường Tối đa khi Xác nhận khai báo Code phí — FE chặn, báo trường bắt buộc",
     1, "Bảng mô tả trường: Tối đa (★ bắt buộc)"),
    ("SC-28", FEATURE, "Thiết lập công thức", "Negative Path",
     "Nhập hàm MONTHS_BETWEEN với tham số không phải ngày (VD: MONTHS_BETWEEN(100,200)) — báo lỗi",
     1, "Mục YCNV: 'bắt buộc phải nhập 2 tham số có định dạng là ngày'"),

    # === BOUNDARY VALUE ===
    ("SC-29", FEATURE, "Thiết lập công thức", "Boundary Value",
     "Nhập công thức đúng 300 ký tự (biên trên) — hệ thống chấp nhận",
     1, "Bảng mô tả trường: 'Nhập tối đa 300 ký tự'"),
    ("SC-30", FEATURE, "Thiết lập công thức", "Boundary Value",
     "Nhập công thức 301 ký tự (vượt biên trên) — hệ thống không cho nhập thêm hoặc báo lỗi",
     1, "Bảng mô tả trường: 'Nhập tối đa 300 ký tự'"),
    ("SC-31", FEATURE, "Thiết lập công thức", "Boundary Value",
     "Nhập công thức chỉ 1 ký tự hợp lệ (VD: 0) — kiểm tra hệ thống xử lý",
     1, "Bảng mô tả trường: Công thức - ký tự số được phép"),
    ("SC-32", FEATURE, "Quy tắc tính phí", "Boundary Value",
     "Nhập Tối thiểu = 0 — kiểm tra hệ thống chấp nhận giá trị biên dưới",
     1, "Bảng mô tả trường: Tối thiểu (Number)"),
    ("SC-33", FEATURE, "Quy tắc tính phí", "Boundary Value",
     "Nhập Tối đa = giá trị rất lớn (VD: 999,999,999,999.99) — kiểm tra biên trên Number",
     1, "Bảng mô tả trường: Tối đa (Number); QTC-01.4 định dạng Number"),
    ("SC-34", FEATURE, "Quy tắc tính phí", "Boundary Value",
     "Nhập Tối thiểu > Tối đa — kiểm tra validate logic Min ≤ Max",
     1, "Bảng mô tả trường: Tối thiểu và Tối đa — logic nghiệp vụ"),
    ("SC-35", FEATURE, "Quy tắc tính phí", "Boundary Value",
     "Nhập Tối thiểu = Tối đa (giá trị bằng nhau) — kiểm tra hệ thống chấp nhận",
     1, "Bảng mô tả trường: Tối thiểu và Tối đa — biên đặc biệt"),
    ("SC-36", FEATURE, "Quy tắc tính phí", "Boundary Value",
     "Nhập Tối thiểu/Tối đa là số âm — kiểm tra hệ thống xử lý",
     1, "Bảng mô tả trường: Tối thiểu/Tối đa (Number)"),

    # === UI/UX & FIELD VALIDATION ===
    ("SC-37", FEATURE, "Quy tắc tính phí", "UI/UX & Field Validation",
     "Kiểm tra hiển thị phân vùng Quy tắc tính phí khi KHÔNG tích 'Khai báo theo nhóm KH' — chỉ hiển thị Công thức, Tối thiểu, Tối đa (không có cột Nhóm KH)",
     1, "Mục YCNV: 'Khi không lựa chọn Khai báo theo nhóm KH... chỉ khai báo 1 Công thức'"),
    ("SC-38", FEATURE, "Quy tắc tính phí", "UI/UX & Field Validation",
     "Kiểm tra hiển thị phân vùng Quy tắc tính phí khi CÓ tích 'Khai báo theo nhóm KH' — hiển thị thêm cột Nhóm KH và nút '+ Thêm nhóm KH'",
     1, "Mục YCNV: 'Khi lựa chọn Khai báo theo nhóm KH... hiển thị thêm trường Nhóm KH'"),
    ("SC-39", FEATURE, "Thiết lập công thức", "UI/UX & Field Validation",
     "Kiểm tra trường Công thức tại màn hình Thiết lập là readonly (◎) — chỉ nhập qua click Biến hoặc bàn phím ảo",
     1, "Bảng mô tả trường: Công thức (◎ disable nhập trực tiếp)"),
    ("SC-40", FEATURE, "Thiết lập công thức", "UI/UX & Field Validation",
     "Kiểm tra danh sách Trường giá trị tính phí (◎ Combobox) hiển thị đúng theo Loại tính phí đã chọn",
     1, "Bảng mô tả trường: Trường giá trị tính phí (◎ Combobox)"),
    ("SC-41", FEATURE, "Thiết lập công thức", "UI/UX & Field Validation",
     "Kiểm tra hệ thống tự động loại bỏ khoảng trắng và chuyển toàn bộ ký tự chữ thành viết hoa khi lưu công thức",
     1, "Bảng mô tả trường: 'hệ thống tự động loại bỏ các khoảng trắng và chuyển toàn bộ ký tự chữ thành viết hoa'"),
    ("SC-42", FEATURE, "Quy tắc tính phí", "UI/UX & Field Validation",
     "Kiểm tra Dropdown Nhóm KH chỉ hiển thị nhóm KH tương ứng với Loại KH đã chọn tại Thông tin chung",
     1, "Bảng mô tả trường: 'Hiển thị danh sách Nhóm KH tương ứng với từng loại KH đã khai báo trên hệ thống'"),
    ("SC-43", FEATURE, "Quy tắc tính phí", "UI/UX & Field Validation",
     "Kiểm tra trường Công thức tại phân vùng Quy tắc tính phí hiển thị đúng công thức đã thiết lập (readonly)",
     1, "Bảng mô tả trường: Công thức (★) Text — 'Hiển thị công thức do người dùng thiết lập'"),
    ("SC-44", FEATURE, "Quy tắc tính phí", "UI/UX & Field Validation",
     "Kiểm tra Number format hiển thị đúng cho Tối thiểu/Tối đa — phân cách nghìn bằng dấu phẩy, 2 số thập phân",
     1, "QTC-01.4: Định dạng Number"),

    # === BUSINESS LOGIC ===
    ("SC-45", FEATURE, "Quy tắc tính phí", "Business Logic",
     "Phê duyệt Code phí bao gồm Quy tắc tính phí — Checker duyệt thành công, dữ liệu công thức chính thức",
     1, "Mục YCNV: 'việc phê duyệt Công thức tính phí được thực hiện đồng thời với việc phê duyệt Code phí'"),
    ("SC-46", FEATURE, "Quy tắc tính phí", "Business Logic",
     "Chỉnh sửa Quy tắc tính phí sau khi đã duyệt — chỉ được sửa giá trị số học, KHÔNG được sửa hàm/biến",
     1, "Mục YCNV: 'chỉ được chỉnh sửa các giá trị là số học; không cho phép sửa các hàm tính toán và các giá trị tính phí'"),
    ("SC-47", FEATURE, "Quy tắc tính phí", "Business Logic",
     "Cố gắng sửa hàm tính toán hoặc Biến trong công thức đã duyệt — hệ thống không cho phép",
     1, "Mục YCNV: 'không cho phép sửa các hàm tính toán và các giá trị tính phí'"),
    ("SC-48", FEATURE, "Quy tắc tính phí", "Business Logic",
     "Chỉnh sửa Code phí nhưng không thay đổi công thức/Tối thiểu/Tối đa — FE disable nút hoặc cảnh báo 'Không có thay đổi'",
     1, "QTC-14.1: No-Change Guard"),
    ("SC-49", FEATURE, "Quy tắc tính phí", "Business Logic",
     "Xác nhận khai báo Code phí với công thức đã thiết lập — luồng Maker tạo bản ghi Chờ duyệt",
     1, "Mục YCNV tham chiếu US02; QTC-12: Maker-Checker"),

    # === DATA INTEGRITY ===
    ("SC-50", FEATURE, "Quy tắc tính phí", "Data Integrity",
     "Kiểm tra khi khai báo theo nhóm KH — không cho chọn trùng Nhóm KH cho cùng Code phí",
     1, "Mục YCNV: 'mỗi công thức áp dụng riêng cho mỗi nhóm KH' — logic unique"),
    ("SC-51", FEATURE, "Thiết lập công thức", "Data Integrity",
     "Kiểm tra Biến trong công thức chỉ thuộc danh sách Biến có trạng thái = Hoạt động",
     1, "Bảng mô tả trường: 'điều kiện tính phí có trạng thái = Hoạt động'"),
    ("SC-52", FEATURE, "Quy tắc tính phí", "Data Integrity",
     "Kiểm tra đồng bộ dữ liệu công thức giữa màn hình Thiết lập công thức và phân vùng Quy tắc tính phí",
     1, "Bảng mô tả trường: Công thức hiển thị từ màn hình Thiết lập"),

    # === NFR ===
    ("SC-53", FEATURE, "Thiết lập công thức", "NFR",
     "Spam click nút Xác nhận tại Thiết lập công thức — hệ thống chỉ xử lý 1 lần, không tạo dữ liệu trùng",
     1, "QTC-12; NFR bắt buộc spam-click cho hành động Xác nhận Thêm mới"),
    ("SC-54", FEATURE, "Quy tắc tính phí", "NFR",
     "Spam click nút Xác nhận khi Chỉnh sửa Code phí (phần công thức) — hệ thống chỉ xử lý 1 lần",
     1, "QTC-12; NFR bắt buộc spam-click cho hành động Xác nhận Chỉnh sửa"),
    ("SC-55", FEATURE, "Quy tắc tính phí", "NFR",
     "Spam click nút Xóa tại Tác vụ Pending (Maker xóa bản ghi chờ duyệt) — hệ thống chỉ xử lý 1 lần",
     1, "QTC-12; NFR bắt buộc spam-click cho hành động Xóa Pending"),
    ("SC-56", FEATURE, "Quy tắc tính phí", "NFR",
     "Spam click nút Phê duyệt tại Tác vụ chờ duyệt (Checker) — hệ thống chỉ xử lý 1 lần",
     1, "QTC-12; NFR bắt buộc spam-click cho hành động Phê duyệt"),
    ("SC-57", FEATURE, "Quy tắc tính phí", "NFR",
     "Spam click nút Từ chối tại Tác vụ chờ duyệt (Checker) — hệ thống chỉ xử lý 1 lần",
     1, "QTC-12; NFR bắt buộc spam-click cho hành động Từ chối"),
]
