#!/usr/bin/env python3
"""US06 Part C data: Test Case Coverage scenarios."""

# Format: (ID, Feature, Module, TestType, Title, EstTC, Traceability)
DATA = [
    # ==========================================
    # 🟢 Happy Path
    # ==========================================
    ("SC-01", "Khai báo Biểu phí", "Thêm mới Biểu phí", "Happy Path",
     "Thêm mới Biểu phí thành công với đầy đủ thông tin hợp lệ (tất cả trường bắt buộc + Link iDoc)",
     1, 'Mục "Thêm mới Biểu phí", Flowchart Thêm mới Bước 1→7c'),
    ("SC-02", "Khai báo Biểu phí", "Thêm mới – Gán Code phí", "Happy Path",
     "Gán Code phí bằng tích chọn cây SPDV thành công – tích chọn SPDV cấp cha, hệ thống tự động tích chọn con và Code phí",
     1, 'Mục "Thêm mới", đoạn tích chọn tại trường SPDV/Code phí'),
    ("SC-03", "Khai báo Biểu phí", "Thêm mới – Gán Code phí", "Happy Path",
     "Gán Code phí bằng Upload file Excel thành công (tham chiếu US07)",
     1, 'Mục "Thêm mới", đoạn Upload file danh sách code phí'),
    ("SC-04", "Khai báo Biểu phí", "Thêm mới – Sửa Code phí", "Happy Path",
     "Sửa Điều kiện tính phí (Mô tả, Giá trị) và Quy tắc tính phí (giá trị số, Tối thiểu, Tối đa) của Code phí trong Biểu phí thành công",
     1, 'Mục "Thêm mới", đoạn Hành động Chỉnh sửa Code phí'),
    ("SC-05", "Khai báo Biểu phí", "Thêm mới – Xem Code phí", "Happy Path",
     "Xem chi tiết Code phí trong luồng Thêm mới Biểu phí – hiển thị đúng như màn hình Xem tại Danh mục SPDV",
     1, 'Mục "Thêm mới" P41 "Xem chi tiết Code phí"'),
    ("SC-05b", "Khai báo Biểu phí", "Thêm mới – Bỏ gắn Code phí", "Happy Path",
     "Bỏ gắn (Xóa) Code phí khỏi Biểu phí trong luồng Thêm mới → Code phí biến mất khỏi lưới Thông tin chi tiết",
     1, 'Mục "Thêm mới" P42 "Bỏ gắn Code phí"'),
    ("SC-06", "Khai báo Biểu phí", "Thêm mới – Tác vụ chờ duyệt", "Happy Path",
     "Sau Maker khai báo → bản ghi chờ duyệt với hành động 'Thêm mới' (không sửa Code phí)",
     1, 'Mục "Thêm mới", đoạn P43-P44'),
    ("SC-07", "Khai báo Biểu phí", "Thêm mới – Tác vụ chờ duyệt", "Happy Path",
     "Sau Maker khai báo + sửa Code phí → bản ghi chờ duyệt với hành động 'Thêm mới – Sửa Code phí'",
     1, 'Mục "Thêm mới", đoạn P45'),
    ("SC-08", "Khai báo Biểu phí", "Chỉnh sửa – Chưa hiệu lực", "Happy Path",
     "Chỉnh sửa Biểu phí Chưa hiệu lực: sửa thông tin chung (trừ Mã) + sửa Code phí thành công",
     1, 'Mục "Chỉnh sửa", trạng thái Chưa hiệu lực P55-P60'),
    ("SC-09", "Khai báo Biểu phí", "Chỉnh sửa – Đang hiệu lực", "Happy Path",
     "Chỉnh sửa Biểu phí Đang hiệu lực: chỉ sửa Ngày hết hiệu lực hợp lệ (> Ngày HT và > Ngày hiệu lực)",
     1, 'Mục "Chỉnh sửa", trạng thái Đang hiệu lực P62 + BA QA-01.6'),
    ("SC-10", "Khai báo Biểu phí", "Chỉnh sửa – Hết hiệu lực", "Happy Path",
     "Chỉnh sửa Biểu phí Hết hiệu lực: chuyển đổi Code phí sang Biểu phí mới (tham chiếu US09)",
     1, 'Mục "Chỉnh sửa", trạng thái Hết hiệu lực P63'),
    ("SC-11", "Khai báo Biểu phí", "Chỉnh sửa – Tác vụ chờ duyệt", "Happy Path",
     "Sau Maker chỉnh sửa → bản ghi chờ duyệt hành động 'Chỉnh sửa' hoặc 'Chỉnh sửa – Sửa Code phí'",
     1, 'Mục "Chỉnh sửa", đoạn P64-P66'),

    # ==========================================
    # 🔴 Negative Path & Exception Handling
    # ==========================================
    ("SC-12", "Khai báo Biểu phí", "Thêm mới – Validation FE", "Negative Path",
     "Thêm mới: Bỏ trống từng trường bắt buộc (Mã, Tên, Ngày ban hành, Ngày hiệu lực, Ngày hết hiệu lực, Số VB, Tên VB) → FE chặn",
     1, 'Bảng mô tả trường, tất cả trường ★'),
    ("SC-13", "Khai báo Biểu phí", "Thêm mới – Validation FE", "Negative Path",
     "Thêm mới: Mã Biểu phí trùng với Mã đã tồn tại → BE trả lỗi unique",
     1, 'Bảng mô tả trường R5, cột Mô tả "Mã Biểu phí là duy nhất"'),
    ("SC-14", "Khai báo Biểu phí", "Thêm mới – Validation FE", "Negative Path",
     "Thêm mới: Ngày ban hành > Ngày hệ thống (ngày tương lai) → FE chặn",
     1, 'Bảng mô tả trường R7, ràng buộc "Không chọn ngày tương lai"'),
    ("SC-15", "Khai báo Biểu phí", "Thêm mới – Validation FE", "Negative Path",
     "Thêm mới: Ngày hiệu lực < Ngày hệ thống → FE chặn",
     1, 'Bảng mô tả trường R8, ràng buộc "Không chọn ngày quá khứ"'),
    ("SC-16", "Khai báo Biểu phí", "Thêm mới – Validation FE", "Negative Path",
     "Thêm mới: Ngày hết hiệu lực < Ngày hiệu lực → FE chặn",
     1, 'Bảng mô tả trường R9, ràng buộc "Ngày hết hiệu lực >= Ngày hiệu lực"'),
    ("SC-17", "Khai báo Biểu phí", "Thêm mới – Validation FE", "Negative Path",
     "Thêm mới: Không gán Code phí nào (lưới trống) → FE disable nút Xác nhận",
     1, 'BA xác nhận QA-01.8 "ít nhất 1 Code phí"'),
    ("SC-18", "Khai báo Biểu phí", "Thêm mới – Upload", "Negative Path",
     "Upload file sai định dạng (không phải .xlsx) hoặc vượt dung lượng → toast lỗi",
     1, 'QTC-07 Upload file, tham chiếu US07'),
    ("SC-19", "Khai báo Biểu phí", "Thêm mới – Gán Code phí", "Happy Path",
     "Tích chọn trước → Upload file sau → hệ thống THAY THẾ toàn bộ Code phí đã chọn (hành vi mặc định)",
     1, 'Mục "Thêm mới" P25 "mặc định thay thế tất cả"'),
    ("SC-20", "Khai báo Biểu phí", "Thêm mới – Link iDoc", "Negative Path",
     "Nhập Link iDoc không đúng format URL (không bắt đầu http/https) → FE chặn",
     1, 'BA xác nhận QA-02.2 validate URL http/https'),
    ("SC-21", "Khai báo Biểu phí", "Chỉnh sửa – Chặn", "Negative Path",
     "Chỉnh sửa khi có tác vụ Chỉnh sửa/Chỉnh sửa-Sửa Code phí đang Chờ duyệt → hệ thống chặn",
     1, 'Mục "Chỉnh sửa" P52-P53'),
    ("SC-22", "Khai báo Biểu phí", "Chỉnh sửa – Đang hiệu lực", "Negative Path",
     "Chỉnh sửa Biểu phí Đang hiệu lực: Ngày hết hiệu lực mới <= Ngày hệ thống → FE chặn",
     1, 'Mục "Chỉnh sửa" P62 "> Ngày hệ thống"'),
    ("SC-23", "Khai báo Biểu phí", "Chỉnh sửa – Đang hiệu lực", "Negative Path",
     "Chỉnh sửa Biểu phí Đang hiệu lực: Ngày hết hiệu lực mới <= Ngày hiệu lực → FE chặn",
     1, 'Mục "Chỉnh sửa" P62 "> Ngày hiệu lực"'),
    ("SC-24", "Khai báo Biểu phí", "Chỉnh sửa – Chưa hiệu lực", "Negative Path",
     "Chỉnh sửa Biểu phí Chưa hiệu lực: cố gắng thêm Code phí lẻ (không qua Upload) → không cho phép",
     1, 'BA xác nhận QA-01.5 "Không cho phép Thêm mới từng Code phí lẻ"'),
    ("SC-25", "Khai báo Biểu phí", "Thêm mới – Đóng", "Negative Path",
     "Nhấn Đóng khi đang nhập dữ liệu → discard, không popup xác nhận, quay về Danh mục",
     1, 'QTC-15 Hành vi nút Đóng'),
    ("SC-26", "Khai báo Biểu phí", "Chỉnh sửa – BE Exception", "Negative Path",
     "BE validate thất bại khi chỉnh sửa (edge case FE chưa chặn) → hệ thống xử lý an toàn, không crash",
     1, 'QTC-11 FE-First Error Handling'),

    # ==========================================
    # 📐 Boundary Value Analysis
    # ==========================================
    ("SC-27", "Khai báo Biểu phí", "Thêm mới – Boundary", "Boundary Value",
     "Mã Biểu phí: nhập đúng 50 ký tự (max) → lưu thành công",
     1, 'QTC-01.6 Mã max 50 ký tự'),
    ("SC-28", "Khai báo Biểu phí", "Thêm mới – Boundary", "Boundary Value",
     "Mã Biểu phí: nhập 51 ký tự (vượt max) → FE chặn",
     1, 'QTC-01.6 Mã max 50 ký tự'),
    ("SC-29", "Khai báo Biểu phí", "Thêm mới – Boundary", "Boundary Value",
     "Tên Biểu phí: nhập đúng 50 ký tự → lưu thành công",
     1, 'QTC-01.6 Tên max 50 ký tự'),
    ("SC-30", "Khai báo Biểu phí", "Thêm mới – Boundary", "Boundary Value",
     "Link iDoc: nhập đúng 500 ký tự (max) → lưu thành công",
     1, 'BA xác nhận QA-02.2 max 500 ký tự'),
    ("SC-31", "Khai báo Biểu phí", "Thêm mới – Boundary", "Boundary Value",
     "Link iDoc: nhập 501 ký tự → FE chặn",
     1, 'BA xác nhận QA-02.2 max 500 ký tự'),
    ("SC-32", "Khai báo Biểu phí", "Thêm mới – Boundary", "Boundary Value",
     "Ngày hiệu lực = Ngày hệ thống (biên dưới) → lưu thành công",
     1, 'Mục "Thêm mới" P13 ">= Ngày hệ thống"'),
    ("SC-33", "Khai báo Biểu phí", "Thêm mới – Boundary", "Boundary Value",
     "Ngày hết hiệu lực = Ngày hiệu lực (biên dưới) → lưu thành công",
     1, 'Mục "Thêm mới" P13 ">= Ngày hiệu lực"'),
    ("SC-34", "Khai báo Biểu phí", "Thêm mới – Boundary", "Boundary Value",
     "Ngày ban hành = Ngày hệ thống (biên trên) → lưu thành công",
     1, 'Bảng mô tả trường R7 "<= Ngày hệ thống"'),
    ("SC-35", "Khai báo Biểu phí", "Thêm mới – Boundary", "Boundary Value",
     "Gán đúng 1 Code phí (min) → lưu thành công",
     1, 'BA xác nhận QA-01.8 "ít nhất 1 Code phí"'),

    # ==========================================
    # 🎨 UI/UX & Field Validation
    # ==========================================
    ("SC-36", "Khai báo Biểu phí", "Thêm mới – UI", "Field Validation",
     "Trạng thái hiển thị đúng trên Mockup: Thêm mới KHÔNG có trường Trạng thái, Chỉnh sửa CÓ trường Trạng thái readonly",
     1, 'Mockup Thêm mới vs Chỉnh sửa'),
    ("SC-37", "Khai báo Biểu phí", "Thêm mới – UI", "Field Validation",
     "Cây SPDV: Search bar tìm kiếm gần đúng theo Mã SPDV/Tên SPDV/Mã Code phí/Tên Code phí",
     1, 'Bảng mô tả trường R13 "Search bar tìm kiếm nhanh và gần đúng"'),
    ("SC-38", "Khai báo Biểu phí", "Thêm mới – Cascade SPDV", "Business Logic",
     "Cây SPDV: Tích chọn SPDV cấp cha → tự động tích con + Code phí. Bỏ tích cha → tự động bỏ tích con",
     1, 'Bảng mô tả trường R13 hành vi cascade tích/bỏ tích'),
    ("SC-39", "Khai báo Biểu phí", "Thêm mới – Cascade SPDV", "Business Logic",
     "Cây SPDV: Bỏ tích tất cả con đồng cấp → tự động bỏ tích SPDV cha liền trước",
     1, 'Bảng mô tả trường R13 "bỏ tích SPDV cấp cha liền trước"'),
    ("SC-40", "Khai báo Biểu phí", "Thêm mới – UI", "Field Validation",
     "Lưới Thông tin chi tiết: Tất cả trường readonly (◎). Chỉ có nút hành động Chỉnh sửa/Xem/Xóa",
     1, 'Bảng mô tả trường R22-R30 dấu ◎'),
    ("SC-41", "Khai báo Biểu phí", "Thêm mới – UI", "Field Validation",
     "Nhập ký tự đặc biệt XSS/SQL Injection vào trường Mã, Tên, Số VB → FE sanitize hoặc BE chặn",
     1, 'QTC-11 FE-First Error Handling'),
    ("SC-42", "Khai báo Biểu phí", "Chỉnh sửa – UI", "Field Validation",
     "Chỉnh sửa Biểu phí Đang hiệu lực: Chỉ trường Ngày hết hiệu lực enabled, các trường khác disabled",
     1, 'Mục "Chỉnh sửa" P62 + BA QA-01.6'),
    ("SC-43", "Khai báo Biểu phí", "Chỉnh sửa – UI", "Field Validation",
     "Chỉnh sửa không thay đổi gì → FE disable nút Xác nhận hoặc cảnh báo 'Không có thay đổi'",
     1, 'QTC-14.1 No-Change Guard'),

    # ==========================================
    # 🧠 Business Logic & State Transition
    # ==========================================
    ("SC-44", "Khai báo Biểu phí", "Trạng thái Biểu phí", "Business Logic",
     "Trạng thái tự động chuyển Chưa hiệu lực → Đang hiệu lực khi Ngày HT = Ngày hiệu lực (realtime)",
     1, 'Mục "Thêm mới" P47-P49 + BA QA-03.3 "realtime"'),
    ("SC-45", "Khai báo Biểu phí", "Trạng thái Biểu phí", "Business Logic",
     "Trạng thái tự động chuyển Đang hiệu lực → Hết hiệu lực khi Ngày HT > Ngày hết hiệu lực",
     1, 'Mục "Thêm mới" P50 + BA QA-03.3'),
    ("SC-46", "Khai báo Biểu phí", "Maker-Checker", "Business Logic",
     "Checker phê duyệt thành công → Biểu phí hiển thị trên lưới Danh mục chính thức",
     1, 'Mục "Thêm mới" P46 + QTC-12'),
    ("SC-47", "Khai báo Biểu phí", "Maker-Checker", "Business Logic",
     "Checker từ chối → Maker nhận bản ghi tại Tác vụ pending, cho phép Chỉnh sửa lại",
     1, 'QTC-12 mục 2 "Tác vụ pending của tôi"'),
    # SC-48 REMOVED: Redundant với SC-08/09/10 đã cover từng trạng thái riêng
    ("SC-49", "Khai báo Biểu phí", "Thêm mới – Code phí Ngừng HĐ", "Business Logic",
     "Code phí Ngừng hoạt động nằm dưới SPDV Hoạt động VẪN được chọn vào Biểu phí",
     1, 'BA xác nhận QA-01.1'),

    # ==========================================
    # 🔗 Data Integrity & Integration
    # ==========================================
    ("SC-50", "Khai báo Biểu phí", "Toàn vẹn dữ liệu", "Data Integrity",
     "1 Code phí gán nhiều Biểu phí: khoảng thời gian hiệu lực KHÔNG trùng nhau → thành công",
     1, 'BA xác nhận QA-03.1 "khoảng thời gian hiệu lực không trùng"'),
    ("SC-51", "Khai báo Biểu phí", "Toàn vẹn dữ liệu", "Data Integrity",
     "1 Code phí gán nhiều Biểu phí: khoảng thời gian hiệu lực TRÙNG nhau → BE chặn",
     1, 'BA xác nhận QA-03.1'),
    ("SC-52", "Khai báo Biểu phí", "Toàn vẹn dữ liệu", "Data Integrity",
     "Sửa Điều kiện/Quy tắc tính phí tại Biểu phí: thay đổi chỉ áp dụng trong scope Biểu phí, Code phí gốc không ảnh hưởng",
     1, 'Mục "Thêm mới" P37-P40, Flowchart Bước 5.4'),
    ("SC-53", "Khai báo Biểu phí", "Toàn vẹn dữ liệu", "Data Integrity",
     "Upload file thay thế: sau upload, lưới chỉ hiển thị Code phí từ file, Code phí tích chọn trước bị xóa",
     1, 'Mục "Thêm mới" P25 "thay thế tất cả"'),
    ("SC-54", "Khai báo Biểu phí", "Toàn vẹn dữ liệu", "Data Integrity",
     "Chỉnh sửa Biểu phí Chưa hiệu lực: bỏ gắn Code phí → Code phí không còn liên kết sau khi duyệt",
     1, 'Mục "Chỉnh sửa" P61'),

    # ==========================================
    # ⚡ NFR (Spam-click)
    # ==========================================
    ("SC-55", "Khai báo Biểu phí", "NFR – Spam click", "NFR",
     "Spam click nút Xác nhận khi Thêm mới Biểu phí → hệ thống chỉ xử lý 1 request",
     1, 'QTC-12 + NFR spam-click Thêm mới'),
    ("SC-56", "Khai báo Biểu phí", "NFR – Spam click", "NFR",
     "Spam click nút Xác nhận khi Chỉnh sửa Biểu phí → hệ thống chỉ xử lý 1 request",
     1, 'QTC-12 + NFR spam-click Chỉnh sửa'),
    ("SC-57", "Khai báo Biểu phí", "NFR – Spam click", "NFR",
     "Spam click nút Xóa (bỏ gắn Code phí) tại Thông tin chi tiết → không xóa trùng/lỗi",
     1, 'NFR spam-click Xóa Code phí'),
    ("SC-58", "Khai báo Biểu phí", "NFR – Spam click", "NFR",
     "Spam click nút Phê duyệt tại Tác vụ chờ duyệt (Checker) → chỉ xử lý 1 lần",
     1, 'QTC-12 + NFR spam-click Phê duyệt'),
    ("SC-59", "Khai báo Biểu phí", "NFR – Spam click", "NFR",
     "Spam click nút Từ chối tại Tác vụ chờ duyệt (Checker) → chỉ xử lý 1 lần",
     1, 'QTC-12 + NFR spam-click Từ chối'),
    ("SC-60", "Khai báo Biểu phí", "NFR – Spam click", "NFR",
     "Spam click nút Xóa tại Tác vụ Pending (Maker) → chỉ xóa 1 lần",
     1, 'QTC-12 + NFR spam-click Xóa Pending'),

    # ==========================================
    # BỔ SUNG TỪ ĐỐI SOÁT VA (13 SC)
    # ==========================================

    # Happy Path bổ sung
    ("SC-61", "Khai báo Biểu phí", "Chỉnh sửa – Maker-Checker", "Happy Path",
     "Checker phê duyệt thành công tác vụ Chỉnh sửa → Biểu phí cập nhật trên lưới Danh mục",
     1, 'Mục "Chỉnh sửa" P67 + QTC-12'),

    # Negative bổ sung
    ("SC-62", "Khai báo Biểu phí", "Chỉnh sửa – Chưa hiệu lực", "Negative Path",
     "Chỉnh sửa Biểu phí Chưa hiệu lực: cố sửa Mã Biểu phí → FE disable trường Mã, không cho sửa",
     1, 'Mục "Chỉnh sửa" P56 "trừ Mã Biểu phí"'),
    ("SC-63", "Khai báo Biểu phí", "Chỉnh sửa – Maker-Checker", "Negative Path",
     "Checker từ chối tác vụ Chỉnh sửa → Biểu phí giữ nguyên thông tin cũ, bản ghi ở trạng thái Từ chối duyệt",
     1, 'QTC-12 mục 2 + Mục "Chỉnh sửa"'),

    # Boundary bổ sung
    ("SC-64", "Khai báo Biểu phí", "Thêm mới – Boundary", "Boundary Value",
     "Mã Biểu phí: nhập 1 ký tự (biên dưới) → hệ thống chấp nhận",
     1, 'QTC-01.6 Mã – biên dưới'),
    ("SC-65", "Khai báo Biểu phí", "Thêm mới – Boundary", "Boundary Value",
     "Tên Biểu phí: nhập 51 ký tự (vượt biên trên) → FE chặn",
     1, 'QTC-01.6 Tên max 50 ký tự'),
    ("SC-66", "Khai báo Biểu phí", "Thêm mới – Boundary", "Boundary Value",
     "Số văn bản: nhập đúng 50 ký tự (biên trên) → hệ thống chấp nhận",
     1, 'QTC-01.6 Số văn bản max 50 ký tự'),
    ("SC-67", "Khai báo Biểu phí", "Thêm mới – Boundary", "Boundary Value",
     "Tên văn bản: nhập đúng 50 ký tự (biên trên) → hệ thống chấp nhận",
     1, 'QTC-01.6 Tên văn bản max 50 ký tự'),

    # UI/UX bổ sung
    ("SC-68", "Khai báo Biểu phí", "Thêm mới – UI", "Field Validation",
     "Các trường bắt buộc (★) hiển thị dấu (*) đúng trên Mockup Thêm mới; Link iDoc không có dấu (*)",
     1, 'Mockup Thêm mới Biểu phí, Bảng mô tả trường R5-R12'),
    ("SC-69", "Khai báo Biểu phí", "Thêm mới – UI", "Field Validation",
     "Màn hình Thêm mới: không hiển thị nút Tải xuống (chưa có dữ liệu). Chỉnh sửa: hiển thị cả Tải lên + Tải xuống",
     1, 'Mockup Thêm mới vs Mockup Chỉnh sửa'),
    ("SC-70", "Khai báo Biểu phí", "Thêm mới – UI", "Field Validation",
     "Các trường Ngày ban hành, Ngày hiệu lực, Ngày hết hiệu lực hiển thị đúng format dd/mm/yyyy (QTC-01.5)",
     1, 'QTC-01.5 Date format + Bảng mô tả trường R7-R9'),

    # Business Logic bổ sung
    ("SC-71", "Khai báo Biểu phí", "Maker-Checker", "Business Logic",
     "Maker xóa tác vụ Chờ duyệt hoặc Từ chối duyệt tại màn hình Tác vụ Pending của tôi",
     1, 'QTC-12 mục 2 "Xóa: Chờ duyệt hoặc Từ chối duyệt"'),

    # NFR bổ sung – Phân quyền Khối
    ("SC-72", "Khai báo Biểu phí", "NFR – Phân quyền", "NFR",
     "User thuộc Khối KHCN → chỉ thấy Biểu phí có Code phí Loại KH = KHCN/DNSN/CBNV (QTC-10)",
     1, 'QTC-10 Ma trận dữ liệu theo Khối – Biểu phí'),
    ("SC-73", "Khai báo Biểu phí", "NFR – Phân quyền", "NFR",
     "User thuộc Khối KHDN → chỉ thấy Biểu phí có Code phí Loại KH = KHTC (QTC-10)",
     1, 'QTC-10 Ma trận dữ liệu theo Khối – Biểu phí'),

    # ==========================================
    # BỔ SUNG TỪ REVIEW REPORT (7 SC)
    # ==========================================
    ("SC-74", "Khai báo Biểu phí", "Chỉnh sửa – Boundary", "Boundary Value",
     "Chỉnh sửa Đang hiệu lực: Ngày HHL mới = Ngày hệ thống (biên, ràng buộc >) → FE chặn",
     1, 'Mục "Chỉnh sửa" P62 "> Ngày hệ thống" – biên ='),
    ("SC-75", "Khai báo Biểu phí", "Chỉnh sửa – Boundary", "Boundary Value",
     "Chỉnh sửa Đang hiệu lực: Ngày HHL mới = Ngày hiệu lực (biên, ràng buộc >) → FE chặn",
     1, 'Mục "Chỉnh sửa" P62 "> Ngày hiệu lực" – biên ='),
    ("SC-76", "Khai báo Biểu phí", "Thêm mới – Validation FE", "Negative Path",
     "Thêm mới: Ngày hết hiệu lực < Ngày hệ thống (quá khứ) → FE chặn",
     1, 'Bảng mô tả trường R9 "Không chọn ngày quá khứ"'),
    ("SC-77", "Khai báo Biểu phí", "Chỉnh sửa – Chưa hiệu lực", "Negative Path",
     "Chỉnh sửa Chưa hiệu lực: bỏ gắn hết toàn bộ Code phí (lưới trống) → FE disable nút Xác nhận",
     1, 'BA xác nhận QA-01.8 + Mục "Chỉnh sửa" P61'),
    ("SC-78", "Khai báo Biểu phí", "Toàn vẹn dữ liệu", "Data Integrity",
     "Sau Checker duyệt: Code phí cập nhật đồng bộ trên cả lưới Danh mục SPDV và lưới Biểu phí",
     1, 'Mục "Thêm mới" P46 + Mục "Chỉnh sửa" P67'),
    ("SC-79", "Khai báo Biểu phí", "Toàn vẹn dữ liệu", "Data Integrity",
     "Xem Lịch sử tác động sau Thêm mới + Chỉnh sửa: hiển thị đúng Ngày cập nhật, Tác động, Người cập nhật, Người phê duyệt",
     1, 'QTC-08 Lịch sử tác động'),
    ("SC-80", "Khai báo Biểu phí", "Chỉnh sửa – Đóng", "Negative Path",
     "Nhấn Đóng tại màn hình Chỉnh sửa → discard thay đổi, không popup xác nhận, quay về Danh mục",
     1, 'QTC-15 Hành vi nút Đóng – Chỉnh sửa'),
]
