# US38 Part B Merged Data Part 2 - HM2, HM3, HM4

QA_DATA_2 = [
    # ===== HM2: Giới hạn hệ thống & Exception =====
    ("US38-QA-02.1",
     "Bảng TABLE 0 – Bước 1 (ETL DWH), đoạn 'Chi tiết bảng ETL sẽ được thống nhất trong triển khai'",
     "Nếu ETL từ DWH vào ProfiX gặp lỗi (DWH not available, dữ liệu corrupt), ProfiX xử lý thế nào vào đầu ngày hôm sau? Có cơ chế alert/monitoring cho ETL failure? Có retry policy không?",
     "Giới hạn",
     "Đề xuất: Định nghĩa cơ chế xử lý khi ETL thất bại: retry policy, alert cho DWH team, và hành vi ProfiX khi dữ liệu bảo lãnh không được cập nhật đúng giờ.",
     "", "AI+VA"),

    ("US38-QA-02.2",
     "Mục Yêu cầu nghiệp vụ, danh sách trường ETL (Ký quỹ, TSBĐ)",
     "Dữ liệu ETL bao gồm: Có ký quỹ, Tỷ lệ ký quỹ, Giá trị ký quỹ, Có TSBĐ, Loại TSBĐ, Giá trị bảo đảm bằng TSBĐ, Giá trị không có TSBĐ. Câu hỏi: Những trường này ảnh hưởng thế nào đến công thức tính phí bảo lãnh? Mức phí có khác nhau tùy có/không ký quỹ hoặc loại TSBĐ? Tài liệu chưa mô tả công thức tính phí.",
     "Giới hạn",
     "Đề xuất: Bổ sung mô tả công thức tính phí bảo lãnh định kỳ sử dụng tham số ký quỹ và TSBĐ, hoặc tham chiếu rõ đến US nào định nghĩa công thức.",
     "", "VA"),

    ("US38-QA-02.3",
     "Mục Yêu cầu nghiệp vụ, đoạn thu thủ công – API lấy danh sách kỳ phí",
     "T24 gọi API ProfiX lấy danh sách kỳ phí đến hạn. API có giới hạn số kỳ phí trả về không? Nếu KH có hàng trăm kỳ phí đến hạn (nhiều hợp đồng BL), T24 xử lý hết không? Có phân trang không?",
     "Giới hạn",
     "Đề xuất: Xác định giới hạn số bản ghi trả về API response và cơ chế phân trang nếu số lượng kỳ phí vượt ngưỡng.",
     "", "VA"),

    ("US38-QA-02.4",
     "Mục Yêu cầu nghiệp vụ, trường ETL 'Xác định thời hạn? = Có/Không'",
     "US38 chỉ xử lý bảo lãnh 'chưa xác định thời hạn' (Không). Câu hỏi: (a) Bảng ETL đồng bộ cả hai loại hay chỉ loại 'Không'? (b) Nếu khoản BL ban đầu 'Không' → sau đó KH bổ sung thời hạn → trường đổi thành 'Có' qua ETL, ProfiX có dừng theo dõi và không thu phí theo US38 nữa không?",
     "Giới hạn",
     "Đề xuất: Mô tả hành vi ProfiX khi trường 'Xác định thời hạn?' chuyển từ Không → Có: dừng lịch thu phí US38, chuyển cơ chế khác, hay cần can thiệp thủ công.",
     "", "AI+VA"),

    ("US38-QA-02.5",
     "Flowchart 2 – Bước 2, 6, 10 (T24 call API ProfiX)",
     "Nếu API ProfiX timeout/down ở bước 2 (lấy danh sách) hoặc bước 6 (kiểm tra lại) hoặc bước 10 (ghi nhận thành công), T24 xử lý thế nào? Có retry hay rollback giao dịch?",
     "Giới hạn",
     "Đề xuất: BA/SA định nghĩa timeout và cơ chế xử lý cho từng lần call API, đặc biệt bước 10.",
     "", "AI"),

    ("US38-QA-02.6",
     "Flowchart 2 – Bước 10 (T24 hạch toán + call API ProfiX ghi nhận)",
     "Bước 10 gồm 2 action: hạch toán T24 + call API ProfiX. Nếu hạch toán T24 thành công NHƯNG API ProfiX thất bại → T24 đã trừ tiền KH nhưng ProfiX chưa ghi nhận → thu phí trùng ở kỳ sau. Cơ chế rollback/compensation?",
     "Giới hạn",
     "Đề xuất: BA/SA xác định cơ chế consistency: (a) T24 hạch toán SAU KHI ProfiX confirm, HOẶC (b) Có luồng compensation nếu API fail sau hạch toán.",
     "", "AI"),

    ("US38-QA-02.7",
     "Mục Yêu cầu nghiệp vụ, đoạn batch job đầu ngày",
     "Nếu batch job fail giữa chừng (đã xử lý 50/100 khoản), cơ chế resume/retry? Có xử lý idempotent (tránh thu trùng khi retry)?",
     "Giới hạn",
     "Đề xuất: Tham chiếu US35 về cơ chế retry batch. BA xác nhận batch US38 áp dụng cùng cơ chế, bao gồm idempotency check.",
     "", "AI"),

    # ===== HM3: Toàn vẹn dữ liệu =====
    ("US38-QA-03.1",
     "Mục Yêu cầu nghiệp vụ, tham chiếu US35 và US36",
     "US38 refer sang US35 (thu định kỳ) và US36 (truy thu nợ phí). Câu hỏi: Kỳ phí bảo lãnh do US38 sinh ra có quản lý trong cùng bảng dữ liệu kỳ phí với các loại phí định kỳ khác (US35) không? Hay bảo lãnh có bảng riêng?",
     "Toàn vẹn dữ liệu",
     "Đề xuất: Xác nhận cấu trúc dữ liệu: kỳ phí bảo lãnh và kỳ phí thông thường dùng chung hay bảng riêng, để xác định phạm vi test tích hợp.",
     "", "VA"),

    ("US38-QA-03.2",
     "Mục Yêu cầu nghiệp vụ, trường ETL 'Giá trị bảo lãnh'",
     "Giá trị bảo lãnh có thể thay đổi theo thời gian (giải tỏa một phần). Nếu giá trị thay đổi giữa 2 kỳ, ProfiX lấy giá trị nào tính phí: snapshot ETL T-1 (cuối ngày hôm trước) hay giá trị tại thời điểm sinh kỳ phí hay giá trị mới nhất?",
     "Toàn vẹn dữ liệu",
     "Đề xuất: Làm rõ snapshot policy: giá trị bảo lãnh dùng để tính phí lấy tại thời điểm nào.",
     "", "AI+VA"),

    ("US38-QA-03.3",
     "Flowchart 1 – Bước 2.1 (Sinh phí bảo lãnh định kỳ đến hạn & thu tự động)",
     "Flowchart không vẽ nhánh khi bước 2.1 không tìm được khoản bảo lãnh nào đến hạn (kết quả rỗng). Hệ thống ghi log? Cảnh báo? Hay kết thúc bình thường?",
     "Toàn vẹn dữ liệu",
     "Đề xuất: Bổ sung nhánh 'Không có khoản BL đến hạn': batch kết thúc bình thường, ghi log audit.",
     "", "VA"),

    ("US38-QA-03.4",
     "Bảng TABLE 1 – Cột 'Bước' (nhiều dòng trống STT)",
     "Bảng TABLE 1 thiếu số thứ tự cho nhiều bước trong luồng thu thủ công (các dòng cột Bước = trống). Đây là lỗi định dạng tài liệu, cần bổ sung STT để Tester trace test case đúng bước.",
     "Toàn vẹn dữ liệu",
     "Đề xuất: Bổ sung STT đầy đủ cho tất cả bước trong TABLE 1 để đảm bảo traceability với Flowchart.",
     "", "VA"),

    ("US38-QA-03.5",
     "Mục Yêu cầu nghiệp vụ, đoạn thu thủ công + thu tự động",
     "Khi thu thủ công thành công, ProfiX lưu giao dịch. Câu hỏi: (a) Cơ chế đánh dấu kỳ đã thu? Batch job sau đó có 'nhìn thấy' và bỏ qua? (b) API response cho thu thủ công trả về TẤT CẢ kỳ đến hạn hay chỉ kỳ 'Chưa thanh toán'? Cần filter để tránh thu trùng với kỳ đang truy thu (US36).",
     "Toàn vẹn dữ liệu",
     "Đề xuất: ProfiX cần flag/status trên mỗi kỳ (Chưa thu/Đang thu/Đã thu/Thất bại). API response chỉ trả kỳ 'Chưa thanh toán', loại trừ 'Đang xử lý'.",
     "", "AI+VA"),

    ("US38-QA-03.6",
     "Mục Yêu cầu nghiệp vụ, trường ETL 'Trạng thái tài khoản'",
     "Tài liệu ghi 'chỉ lấy tài khoản còn hoạt động'. Nếu khoản BL bị tất toán/đóng giữa kỳ (sau ETL T-1), batch job đầu ngày vẫn thu phí cho khoản đã đóng? Có kiểm tra trạng thái realtime trước khi thu?",
     "Toàn vẹn dữ liệu",
     "Đề xuất: BA xác nhận: (a) ProfiX chỉ dùng ETL T-1 (chấp nhận trễ 1 ngày), HOẶC (b) ProfiX check realtime trước khi thu.",
     "", "AI"),

    ("US38-QA-03.7",
     "Mục Yêu cầu nghiệp vụ, trường ETL 'Thu phí tự động = Có/Không'",
     "Nếu tham số 'Thu phí tự động' bị thay đổi từ Có → Không (hoặc ngược lại) giữa các kỳ, hệ thống áp dụng giá trị nào? Snapshot ETL T-1 hay giá trị tại thời điểm batch job chạy?",
     "Toàn vẹn dữ liệu",
     "Đề xuất: BA xác nhận nguồn dữ liệu quyết định: ETL snapshot T-1 hay call realtime. Nếu dùng ETL, chấp nhận trễ 1 ngày khi thay đổi tham số.",
     "", "AI"),

    # ===== HM4: UI/UX =====
    ("US38-QA-04.1",
     "Mục Giao diện và Mô tả chi tiết các trường (cả 2 = N/A)",
     "US38 ghi Giao diện = N/A. Tuy nhiên luồng thu thủ công diễn ra trên T24. Câu hỏi: (a) ProfiX team chỉ test API response? (b) Trên ProfiX (không phải T24), có màn hình xem danh sách kỳ phí BL đến hạn/lịch sử thu phí không?",
     "UI-UX",
     "Đề xuất: BA xác nhận phạm vi test ProfiX: chỉ API (cần API spec chi tiết) hay bao gồm cả giao diện T24.",
     "", "AI+VA"),

    ("US38-QA-04.2",
     "Flowchart 2 – Bước 4 (T24 hiển thị danh sách kỳ thu phí)",
     "Danh sách kỳ thu phí gồm những thông tin gì? (Số MD, Ngày đến hạn, Số tiền phí, Trạng thái, Loại tiền...). Tài liệu không mô tả cấu trúc API response.",
     "UI-UX",
     "Đề xuất: BA/SA bổ sung API specification: request parameters và response fields cho endpoint 'Lấy danh sách kỳ phí BL đến hạn'.",
     "", "AI+VA"),

    ("US38-QA-04.3",
     "Mục Yêu cầu nghiệp vụ, trường ETL 'Loại TSBĐ' (3 giá trị)",
     "Dữ liệu ETL có trường 'Loại TSBĐ' = Tiền gửi PVCB/Tiền gửi khác/Tài sản khác. Tài liệu mô tả đây là dữ liệu nguồn tính phí nhưng không có màn hình hiển thị. Trên Lịch sử thu phí hay báo cáo, Loại TSBĐ có được hiển thị?",
     "UI-UX",
     "Đề xuất: Xác nhận Loại TSBĐ và các trường BL có hiển thị trên Lịch sử thu phí hay báo cáo để phục vụ đối chiếu.",
     "", "VA"),
]
