"""Data part 2: HM2 + HM3 + HM4 for merged US11 Part B."""

QA_DATA_2 = [
    # ═══ HM2: Giới hạn hệ thống & Exception Handling ═══
    ("US11-QA-02.1",
     "Bảng mô tả trường 'Thêm bộ tham số' - Cột 'Ràng buộc'",
     "Tài liệu không ghi rõ số lượng Bộ tham số tối đa được phép thêm trong 1 CTƯĐ. Giới hạn tối đa là bao nhiêu?",
     "Giới hạn",
     "Đề xuất: Xác định số lượng tối đa để sinh TC Boundary (ví dụ: thêm N+1 bộ tham số → hệ thống chặn).",
     "BOTH"),

    ("US11-QA-02.2",
     "Bảng mô tả trường 'Thêm lịch' - Cột 'Ràng buộc'",
     "Tài liệu không ghi rõ số lượng lịch đánh giá tối đa trong 1 Bộ tham số. Giới hạn là bao nhiêu?",
     "Giới hạn",
     "Đề xuất: Xác định giới hạn để sinh TC Boundary.",
     "BOTH"),

    ("US11-QA-02.3",
     "Bảng mô tả trường 'Thêm nhóm điều kiện' - Cột 'Ràng buộc'",
     "Tài liệu không ghi rõ số lượng Nhóm điều kiện tối đa trong 1 Bộ tham số. Giới hạn là bao nhiêu?",
     "Giới hạn",
     "Đề xuất: Xác định giới hạn để sinh TC Boundary.",
     "BOTH"),

    ("US11-QA-02.4",
     "Bảng mô tả nút '+' (Thêm điều kiện chi tiết) - Cột 'Ràng buộc'",
     "Tài liệu không ghi rõ số lượng điều kiện chi tiết tối đa trong 1 Nhóm điều kiện. Giới hạn là bao nhiêu?",
     "Giới hạn",
     "Đề xuất: Xác định giới hạn để sinh TC Boundary.",
     "BOTH"),

    ("US11-QA-02.5",
     "Bảng mô tả trường 'Thêm SPDV áp dụng' - Cột 'Ràng buộc'",
     "Tài liệu không ghi rõ số lượng SPDV tối đa được thêm vào Chi tiết ưu đãi trong 1 Bộ tham số. Giới hạn là bao nhiêu?",
     "Giới hạn",
     "Đề xuất: Xác định giới hạn để sinh TC Boundary.",
     "BOTH"),

    ("US11-QA-02.6",
     "Bảng mô tả trường 'Operator' - Cột 'Mô tả'",
     "Cần xác nhận danh sách đầy đủ Operator cho từng kiểu dữ liệu: String (=, <>, IN, NOT IN), Number (=, <>, IN, NOT IN, >, >=, <, <=), Date (=, >, >=, <, <=), Time (=, >, >=, <, <=). Danh sách trên đã đầy đủ chưa?",
     "Giới hạn",
     "Đề xuất: BA xác nhận danh sách đầy đủ Operator theo từng kiểu dữ liệu.",
     "VA"),

    ("US11-QA-02.7",
     "Mục 'Xử lý tự động', phần 'Đầu ngày hiệu lực'",
     "Batch Job đánh giá chạy 'đầu ngày hiệu lực'. Nếu Job fail giữa chừng (lỗi hệ thống, timeout), hệ thống xử lý thế nào? Có cơ chế retry/rollback không?",
     "Giới hạn",
     "Đề xuất: Cần cơ chế retry tự động (ví dụ: 3 lần) và ghi log lỗi. Nếu vẫn fail → gửi alert cho Admin.",
     "AI"),

    # ═══ HM3: Toàn vẹn dữ liệu & Ràng buộc ═══
    ("US11-QA-03.1",
     "Bảng mô tả trường 'Nguồn dữ liệu' - Cột 'Mô tả'",
     "Bảng mô tả có mâu thuẫn/lỗi copy-paste: Dòng cuối ghi 'Khi Loại ưu đãi = Theo Tài khoản, nguồn dữ liệu = ETL Khách hàng/ETL Thẻ' — phải là 'Theo Thẻ' chứ không phải 'Theo Tài khoản'. Ngoài ra: Loại ưu đãi = Theo TK và Theo Thẻ → Nguồn DL mặc định là gì? Người dùng có thể thay đổi không?",
     "Toàn vẹn dữ liệu",
     "Đề xuất: (a) Sửa lỗi copy-paste: Dòng cuối = 'Khi Loại ưu đãi = Theo Thẻ'. (b) BA bổ sung mapping đầy đủ Loại ưu đãi → Nguồn DL mặc định + quy tắc enabled/disabled.",
     "BOTH"),

    ("US11-QA-03.2",
     "Bảng mô tả trường 'Loại ưu đãi' - Cột 'Ràng buộc'",
     "Khi người dùng đã khai báo các điều kiện đánh giá rồi thay đổi Loại ưu đãi → Nguồn dữ liệu thay đổi. Các điều kiện đã nhập có bị xóa toàn bộ không?",
     "Toàn vẹn dữ liệu",
     "Đề xuất: FE hiển thị cảnh báo 'Thay đổi Loại ưu đãi sẽ xóa toàn bộ điều kiện đánh giá đã nhập' và yêu cầu xác nhận trước khi xóa.",
     "VA"),

    ("US11-QA-03.3",
     "Bảng mô tả trường 'SPDV' - Cột 'Mô tả'",
     "Tài liệu ghi: 'Các SPDV không có quan hệ cha con trong cùng 1 CTƯĐ'. (a) SPDV có được chọn trùng giữa các dòng trong cùng 1 Bộ tham số không? (b) Có được chọn trùng giữa các Bộ tham số khác nhau không?",
     "Toàn vẹn dữ liệu",
     "Đề xuất: BA xác nhận ràng buộc unique SPDV trong phạm vi: (1) cùng Bộ tham số, (2) toàn CTƯĐ.",
     "BOTH"),

    ("US11-QA-03.4",
     "Bảng mô tả trường 'Số văn bản_Tên viết tắt CTƯĐ' - Cột 'Ràng buộc'",
     "Tài liệu ghi tối đa 20 ký tự, bắt buộc có dấu gạch dưới, phía trước là số, phía sau chữ viết hoa. (a) 20 ký tự tính cả dấu gạch dưới không? (b) Có giới hạn TỐI THIỂU không? (c) Xác nhận phần trước dấu gạch dưới chỉ nhận ký tự số?",
     "Toàn vẹn dữ liệu",
     "Đề xuất: 20 ký tự bao gồm cả dấu gạch dưới. Tối thiểu: 1 số + '_' + 1 chữ = 3 ký tự. Phía trước chỉ là số.",
     "BOTH"),

    ("US11-QA-03.5",
     "Bảng mô tả trường 'Email CBNV đầu mối' - Cột 'Mô tả'",
     "Email CBNV đầu mối: (a) Có thể nhập nhiều email (cách nhau dấu phẩy/chấm phẩy) hay chỉ 1 email? (b) FE validate format email real-time (khi blur) hay chỉ khi nhấn Xác nhận? (c) Domain bắt buộc pvcombank.com.vn?",
     "Toàn vẹn dữ liệu",
     "Đề xuất: (a) 1 email duy nhất (tên trường dùng số ít). (b) Validate khi blur. (c) Domain pvcombank.com.vn bắt buộc.",
     "BOTH"),

    ("US11-QA-03.6",
     "Mục 'Thêm mới CTƯĐ', phần Thông tin chung, trường 'Ngày ban hành'",
     "Bảng mô tả trường ghi Ngày ban hành = ★ (bắt buộc) với ràng buộc 'Không chọn ngày tương lai'. Nhưng yêu cầu nghiệp vụ ghi 'Ngày hiệu lực >= Ngày ban hành (nếu có)' — mệnh đề '(nếu có)' ngầm cho phép bỏ trống, mâu thuẫn với ★.",
     "Toàn vẹn dữ liệu",
     "Đề xuất: BA làm rõ: Ngày ban hành bắt buộc (★) hay không bắt buộc?",
     "AI"),

    ("US11-QA-03.7",
     "Mục 'Thêm mới CTƯĐ', phần Điều kiện đánh giá, ràng buộc cặp (Trường ĐK + Operator)",
     "Bảng mô tả ghi: 'một cặp (Trường điều kiện + Operator) không được trùng lặp'. Ràng buộc unique này áp dụng trong phạm vi 1 nhóm điều kiện hay toàn bộ bộ tham số?",
     "Toàn vẹn dữ liệu",
     "Đề xuất: Phạm vi unique = trong 1 nhóm điều kiện. Cần BA xác nhận.",
     "AI"),

    ("US11-QA-03.8",
     "Mục 'Thêm mới CTƯĐ', phần Chi tiết ưu đãi, trường 'Kỳ'",
     "Tài liệu ghi: 'ưu đãi trong cùng 1 kỳ phải có Kênh hoặc SPDV khác nhau'. Toán tử 'hoặc': (a) Khác Kênh HOẶC khác SPDV (chỉ cần 1), hay (b) Khác cả Kênh VÀ SPDV?",
     "Toàn vẹn dữ liệu",
     "Đề xuất: Hiểu theo (a): chỉ cần khác ít nhất 1 trong 2. Cần BA xác nhận.",
     "AI"),

    ("US11-QA-03.9",
     "Bảng Batch Job - Hàng 'Đầu ngày hiệu lực, Bước 1'",
     "Batch job lấy Bộ tham số 'không bao gồm điều kiện đánh giá Trạng thái KH = NEW'. Xác nhận: Batch job loại trừ toàn bộ Bộ tham số CÓ ĐK này, hay chỉ bỏ qua ĐK đó nhưng vẫn xét các ĐK còn lại?",
     "Toàn vẹn dữ liệu",
     "Đề xuất: BA làm rõ logic loại trừ — loại cả Bộ tham số hay chỉ bỏ 1 ĐK.",
     "VA"),

    # ═══ HM4: UI/UX & Giao diện ═══
    ("US11-QA-04.1",
     "Mockup UI, khu vực 'Thiết lập chương trình' - Thông tin chung",
     "Mockup hiển thị trường 'Loại ưu đãi' ở vùng giữa form (giữa cột trái/phải), tách biệt với các trường khác. Bảng mô tả xếp vào nhóm THÔNG TIN CHUNG (sau Khối). Layout thực tế theo mockup hay bảng mô tả?",
     "UI-UX",
     "Đề xuất: BA cung cấp mockup có annotation rõ vị trí trường Loại ưu đãi.",
     "BOTH"),

    ("US11-QA-04.2",
     "Mockup UI - So sánh Chi tiết ưu đãi: Bộ tham số 1 vs Bộ tham số 2",
     "Mockup Bộ tham số 1: cột Kênh, Kỳ, SPDV, Tỷ lệ ưu đãi. Bộ tham số 2 có thêm cột '#' (STT) và cột 'Tần suất'. Đây là lỗi mockup hay các cột này luôn xuất hiện?",
     "UI-UX",
     "Đề xuất: BA xác nhận cột '#' và 'Tần suất' có tồn tại hay là lỗi mockup.",
     "BOTH"),

    ("US11-QA-04.3",
     "Mockup UI - Operator And/Or giữa các Nhóm điều kiện",
     "Mockup hiển thị dropdown 'And/Or' bên trái Nhóm điều kiện số 2 trở đi. Giá trị mặc định khi thêm mới Nhóm điều kiện là 'And' hay 'Or'? Người dùng có thể thay đổi không?",
     "UI-UX",
     "Đề xuất: BA xác nhận giá trị mặc định và hành vi dropdown And/Or.",
     "VA"),

    ("US11-QA-04.4",
     "Mockup UI - Lịch đánh giá, Lần 1",
     "Mockup hiển thị Lần đánh giá 1 không có icon xóa (x), trong khi Lần 2, 3, 4 có. Xác nhận Lần 1 không thể xóa?",
     "UI-UX",
     "Đề xuất: Lần 1 mặc định và không thể xóa.",
     "VA"),

    ("US11-QA-04.5",
     "Mockup UI - Bảng Điều kiện đánh giá",
     "Mockup hiển thị cột '#' (STT dòng) ở bảng Điều kiện, nhưng bảng mô tả trường không liệt kê cột '#'. Cột STT này có tồn tại trên giao diện thực tế không?",
     "UI-UX",
     "Đề xuất: Cột '#' là STT tự động, không cần user nhập. Cần BA xác nhận.",
     "AI"),

    ("US11-QA-04.6",
     "Bảng mô tả trường 'Số văn bản_Tên viết tắt CTƯĐ' - Label hiển thị",
     "Label trên UI của trường này là gì? Mockup không hiển thị rõ label. Tên đầy đủ hiển thị trên màn hình như thế nào?",
     "UI-UX",
     "Đề xuất: BA xác nhận label chính xác trên UI.",
     "VA"),

    ("US11-QA-04.7",
     "Mục 'Chỉnh sửa CTƯĐ', Flowchart Bước 3.a vs Yêu cầu nghiệp vụ",
     "Flowchart 3.a ghi: 'Chỉ cho phép chỉnh Ngày hết hiệu lực và chi tiết ưu đãi'. Text yêu cầu nghiệp vụ cho phép sửa cả 'Lịch đánh giá'. Flowchart bị thiếu so với text.",
     "UI-UX",
     "Đề xuất: Text là chuẩn. Flowchart cần bổ sung 'Lịch đánh giá'. BA xác nhận.",
     "AI"),

    ("US11-QA-04.8",
     "Mục 'Chỉnh sửa CTƯĐ', Flowchart Bước 3.1 vs Yêu cầu nghiệp vụ",
     "Flowchart 3.1: 'cho phép Chỉnh sửa toàn bộ trừ Mã CTƯĐ'. Text ghi: trừ cả 'Mã CTƯĐ và Số VB_Tên viết tắt'. Flowchart thiếu đề cập 'Số VB_Tên viết tắt'.",
     "UI-UX",
     "Đề xuất: Text là chuẩn (trừ cả 2 trường). Flowchart cần bổ sung. BA xác nhận.",
     "AI"),

    ("US11-QA-04.9",
     "Bảng mô tả trường 'Ngày hết hiệu lực' - Cột 'Ràng buộc'",
     "Tài liệu cho phép Ngày HHL = Ngày HL (CTƯĐ chỉ hiệu lực 1 ngày). Xác nhận đây là kịch bản nghiệp vụ hợp lệ hay cần enforce Ngày HHL > Ngày HL?",
     "UI-UX",
     "Đề xuất: Cần BA xác nhận kịch bản hiệu lực 1 ngày là hợp lệ.",
     "VA"),

    ("US11-QA-04.10",
     "Bảng mô tả trường 'Giá trị ưu đãi' - Cột 'Mô tả'",
     "Tài liệu ghi hành vi toggle: 'Khi thay đổi Loại ưu đãi → hệ thống tự động clear toàn bộ giá trị đã nhập trước đó'. Xác nhận: clear chỉ giá trị ưu đãi/tỷ lệ ưu đãi, hay clear TOÀN BỘ các trường trong Chi tiết ưu đãi (Kênh, Kỳ, SPDV)?",
     "UI-UX",
     "Đề xuất: Chỉ clear giá trị/tỷ lệ ưu đãi. Kênh, Kỳ, SPDV giữ nguyên. Cần BA xác nhận.",
     "VA"),
]
