# -*- coding: utf-8 -*-
# US13 Part C — Test Case Coverage Data
# Feature: Khai báo CTƯĐ không xác định sẵn danh sách khách hàng áp dụng

FEATURE = "Khai báo CTƯĐ không xác định sẵn danh sách KH"

# (SC_ID, Feature, Module, Type, Title, Traceability)
DATA_PART1 = [
    # ========== MODULE: THÊM MỚI – THÔNG TIN CHUNG ==========
    ("SC-01", FEATURE, "Thêm mới – Thông tin chung", "Happy Path",
     "Thêm mới CTƯĐ với đầy đủ Thông tin chung hợp lệ (Tên, Ngày ban hành, Ngày HL, Ngày HHL, Số văn bản, Tên văn bản, Tên viết tắt, Đối tượng thu phí, Khối, Loại ưu đãi, Hình thức) → Hệ thống ghi nhận và cho phép tiếp tục khai báo",
     'Mục "Thêm mới CTƯĐ" – *"Các thông tin được khai báo bao gồm: Thông tin chung, Chu kỳ áp dụng, Điều kiện áp dụng, Chi tiết ưu đãi"*'),
    ("SC-02", FEATURE, "Thêm mới – Thông tin chung", "Happy Path",
     "Chọn Đối tượng thu phí = Khách hàng → Loại ưu đãi cho phép chọn 1 trong: Theo Khách hàng / Theo Tài khoản / Theo Thẻ / Theo Giao dịch",
     'QA-01.1, BA xác nhận – *"Trường Loại ưu đãi đều có tại màn hình khai báo CTUD xác định sẵn DSKH và không xác định sẵn DSKH"*'),
    ("SC-03", FEATURE, "Thêm mới – Thông tin chung", "Happy Path",
     "Chọn Đối tượng thu phí = Merchant → Loại ưu đãi mặc định = Theo Giao dịch (readonly), Loại tiền tệ mặc định = VND (readonly)",
     'Tham chiếu US12 – *"Merchant: Loại ưu đãi mặc định là Theo Giao dịch và không được phép chỉnh sửa"*'),
    ("SC-04", FEATURE, "Thêm mới – Thông tin chung", "Happy Path",
     "Chọn Hình thức = Liên tục → Hệ thống KHÔNG hiển thị phân vùng Chu kỳ áp dụng",
     'Mockup image2 – *"Hình thức: Liên tục"* – Phân vùng Chu kỳ áp dụng không xuất hiện'),
    ("SC-05", FEATURE, "Thêm mới – Thông tin chung", "Happy Path",
     "Chọn Hình thức = Theo chu kỳ → Hệ thống hiển thị phân vùng Chu kỳ áp dụng (Hàng tuần / Hàng tháng)",
     'Mockup image3 – *"Hình thức: Theo chu kỳ"* – Hiển thị Chu kỳ áp dụng'),
    ("SC-06", FEATURE, "Thêm mới – Thông tin chung", "Negative Path",
     "Bỏ trống từng trường bắt buộc (Tên CTƯĐ / Ngày ban hành / Ngày HL / Ngày HHL / Số văn bản / Tên văn bản / Tên viết tắt / ĐTPT / Khối / Loại ưu đãi / Hình thức) → FE chặn, hiển thị thông báo lỗi",
     'Bảng "Mô tả chi tiết các trường" – Các trường có ký hiệu ★ (bắt buộc), tham chiếu US12'),
    ("SC-07", FEATURE, "Thêm mới – Thông tin chung", "Negative Path",
     "Nhập Ngày hiệu lực > Ngày hết hiệu lực → FE chặn",
     'Tham chiếu US12 – *"Ngày hiệu lực phải <= Ngày hết hiệu lực"*'),
    ("SC-08", FEATURE, "Thêm mới – Thông tin chung", "Boundary Value",
     "Nhập Tên CTƯĐ đúng 50 ký tự (biên trên) → lưu thành công [QTC-01.6]",
     'QTC-01.6 – *"Trường Tên tối đa 50 ký tự (nếu US không ghi rõ)"*'),
    ("SC-09", FEATURE, "Thêm mới – Thông tin chung", "Boundary Value",
     "Nhập Tên CTƯĐ 51 ký tự (vượt biên) → FE chặn [QTC-01.6]",
     'QTC-01.6 – *"Trường Tên tối đa 50 ký tự (nếu US không ghi rõ)"*'),
    ("SC-10", FEATURE, "Thêm mới – Thông tin chung", "UI/UX & Field Validation",
     "Trường Mã CTƯĐ ở trạng thái Disabled (◎), không cho nhập thủ công, giá trị rỗng khi Thêm mới",
     'QA-04.8, BA đã cập nhật – *"Mã CTƯĐ được tự động sinh SAU khi Checker duyệt"* [QTC-12]'),
    ("SC-11", FEATURE, "Thêm mới – Thông tin chung", "UI/UX & Field Validation",
     "Hình thức hiển thị dạng Radio Button (Theo chu kỳ / Liên tục), loại trừ lẫn nhau",
     'QA-04.6, BA đã cập nhật – Radio Button thay cho Checkbox'),
    ("SC-12", FEATURE, "Thêm mới – Thông tin chung", "UI/UX & Field Validation",
     "Toggle 'Theo danh sách khách hàng' = OFF → Hệ thống hiển thị màn hình US13 (không có CIF/Tên KH)",
     'Lưu đồ Bước 5 – *"Off Toggle Theo danh sách khách hàng"*'),

    # ========== MODULE: THÊM MỚI – ĐIỀU KIỆN ÁP DỤNG ==========
    ("SC-13", FEATURE, "Thêm mới – Điều kiện áp dụng", "Happy Path",
     "Khai báo Nhóm điều kiện với các trường (Nguồn dữ liệu, Tên trường điều kiện, Mô tả, Operator, Giá trị) → Hệ thống ghi nhận",
     'Mockup image2, phân vùng "Điều kiện áp dụng" – *"+ Thêm nhóm điều kiện"*'),
    ("SC-14", FEATURE, "Thêm mới – Điều kiện áp dụng", "Happy Path",
     "Thêm nhiều nhóm điều kiện với quan hệ AND/OR giữa các nhóm → Hệ thống ghi nhận",
     'Mockup image2 – *"And/Or"* dropdown giữa Nhóm điều kiện số 1 và số 2'),
    ("SC-15", FEATURE, "Thêm mới – Điều kiện áp dụng", "Negative Path",
     "Không khai báo bất kỳ Nhóm điều kiện nào → Nhấn Xác nhận → FE chặn hoặc BE trả lỗi",
     'Tham chiếu US12 – Điều kiện áp dụng là phần bắt buộc khai báo'),

    # ========== MODULE: THÊM MỚI – CHU KỲ ÁP DỤNG ==========
    ("SC-16", FEATURE, "Thêm mới – Chu kỳ áp dụng", "Happy Path",
     "Hình thức = Theo chu kỳ, chọn Hàng tuần → Chọn các ngày áp dụng (Thứ Hai, Thứ Ba...) → Hệ thống ghi nhận",
     'Mockup image3, phân vùng "Chu kỳ áp dụng" – *"Hàng tuần / Áp dụng vào thứ"*'),
    ("SC-17", FEATURE, "Thêm mới – Chu kỳ áp dụng", "Happy Path",
     "Hình thức = Theo chu kỳ, chọn Hàng tháng → Chọn Ngày cụ thể hoặc Ngày trong tháng → Hệ thống ghi nhận",
     'Mockup image3, phân vùng "Chu kỳ áp dụng" – *"Hàng tháng / Ngày cụ thể / Ngày trong tháng"*'),

    # ========== MODULE: THÊM MỚI – CHI TIẾT ƯU ĐÃI ==========
    ("SC-18", FEATURE, "Thêm mới – Chi tiết ưu đãi", "Happy Path",
     "Nhấn '+ Thêm SPDV áp dụng' → Hệ thống thêm 1 dòng trống vào bảng Chi tiết ưu đãi → User chọn SPDV và nhập các trường liên quan → Lưu thành công",
     'QA-04.4, BA – *"BA đã mô tả chi tiết các trường trong US"*. Bảng Mô tả trường, "Thêm SPDV áp dụng" Button'),
    ("SC-19", FEATURE, "Thêm mới – Chi tiết ưu đãi", "Happy Path",
     "Toggle 'Ưu đãi theo tỷ lệ' = ON (mặc định) → Hiển thị cột 'Tỷ lệ ưu đãi', ẩn cột 'Giá trị ưu đãi'",
     'Bảng Mô tả trường, Tỷ lệ ưu đãi – *"Hệ thống mặc định hiển thị nếu toggle Ưu đãi theo tỷ lệ = On và ẩn trường Giá trị ưu đãi"*'),
    ("SC-20", FEATURE, "Thêm mới – Chi tiết ưu đãi", "Happy Path",
     "Toggle 'Ưu đãi theo tỷ lệ' = OFF → Hiển thị cột 'Giá trị ưu đãi', ẩn cột 'Tỷ lệ ưu đãi'",
     'Bảng Mô tả trường, Giá trị ưu đãi – *"Hệ thống mặc định hiển thị nếu toggle Ưu đãi theo tỷ lệ = Off và ẩn trường Tỷ lệ ưu đãi"*'),
    ("SC-21", FEATURE, "Thêm mới – Chi tiết ưu đãi", "Happy Path",
     "Khai báo Chi tiết ưu đãi với Loại tiền tệ, Số tiền phí tối thiểu, Số tiền phí tối đa, Trường giá trị kiểm tra, Ngưỡng dừng ưu đãi hợp lệ → Lưu thành công",
     'Mục "Chi tiết ưu đãi" – *"Loại tiền tệ, Số tiền phí tối thiểu, Số tiền phí tối đa, Ngưỡng dừng ưu đãi, Trường giá trị kiểm tra"*'),
    ("SC-22", FEATURE, "Thêm mới – Chi tiết ưu đãi", "Happy Path",
     "Đối tượng thu phí = Merchant → Loại tiền tệ mặc định = VND và không cho phép chỉnh sửa tại từng dòng Chi tiết ưu đãi",
     'Bảng Mô tả trường, Loại tiền tệ – *"Đối tượng thu phí = Merchant, mặc định = VND và không cho phép chỉnh sửa"*'),
    ("SC-23", FEATURE, "Thêm mới – Chi tiết ưu đãi", "Negative Path",
     "Bỏ trống trường bắt buộc tại dòng Chi tiết ưu đãi (SPDV / Tỷ lệ hoặc Giá trị ưu đãi) → FE chặn",
     'Bảng Mô tả trường – SPDV (★), Tỷ lệ ưu đãi (★), Giá trị ưu đãi (★)'),
    ("SC-24", FEATURE, "Thêm mới – Chi tiết ưu đãi", "Negative Path",
     "Không khai báo bất kỳ bản ghi Chi tiết ưu đãi nào → Nhấn Xác nhận → FE chặn",
     'Mục "Thêm mới" – *"Cần đảm bảo phải khai báo ít nhất 1 bản ghi Chi tiết ưu đãi"*'),
    ("SC-25", FEATURE, "Thêm mới – Chi tiết ưu đãi", "Negative Path",
     "Chọn SPDV trùng với SPDV đã khai báo ở dòng khác (cùng khoảng thời gian overlap) → FE/BE chặn",
     'Bảng Mô tả trường, SPDV – *"1 SPDV không được khai báo trùng nhau [...] mà khoảng thời gian hiệu lực overlap nhau"*'),
    ("SC-26", FEATURE, "Thêm mới – Chi tiết ưu đãi", "Negative Path",
     "Chọn SPDV có quan hệ cha-con với SPDV đã khai báo (cùng khoảng thời gian overlap) → FE/BE chặn",
     'Bảng Mô tả trường, SPDV – *"các SPDV có quan hệ cha con mà khoảng thời gian hiệu lực overlap nhau"*'),
    ("SC-27", FEATURE, "Thêm mới – Chi tiết ưu đãi", "Negative Path",
     "Nhập Số tiền phí tối thiểu >= Số tiền phí tối đa → FE chặn",
     'Bảng Mô tả trường, Số tiền phí tối đa – *"Số tiền phí tối thiểu phải < số tiền phí tối đa"*'),
    ("SC-28", FEATURE, "Thêm mới – Chi tiết ưu đãi", "Negative Path",
     "Có nhập Trường giá trị kiểm tra nhưng bỏ trống Ngưỡng dừng ưu đãi → FE chặn",
     'Mục "Chi tiết ưu đãi" – *"Bắt buộc nhập nếu có nhập Trường giá trị kiểm tra"*'),
]

DATA_PART2 = [
    ("SC-29", FEATURE, "Thêm mới – Chi tiết ưu đãi", "Boundary Value",
     "Nhập Tỷ lệ ưu đãi = 0 → FE chặn (phải > 0)",
     'Bảng Mô tả trường, Tỷ lệ ưu đãi – *"Nhập giá trị là số dương > 0 và <= 100"*'),
    ("SC-30", FEATURE, "Thêm mới – Chi tiết ưu đãi", "Boundary Value",
     "Nhập Tỷ lệ ưu đãi = 100 (biên trên) → lưu thành công",
     'Bảng Mô tả trường, Tỷ lệ ưu đãi – *"Nhập giá trị là số dương > 0 và <= 100"*'),
    ("SC-31", FEATURE, "Thêm mới – Chi tiết ưu đãi", "Boundary Value",
     "Nhập Tỷ lệ ưu đãi = 101 (vượt biên) → FE chặn",
     'Bảng Mô tả trường, Tỷ lệ ưu đãi – *"Nhập giá trị là số dương > 0 và <= 100"*'),
    ("SC-32", FEATURE, "Thêm mới – Chi tiết ưu đãi", "Boundary Value",
     "Nhập Giá trị ưu đãi = 0 → FE chặn (phải là số dương > 0)",
     'Bảng Mô tả trường, Giá trị ưu đãi – *"Nhập giá trị là số dương"*'),
    ("SC-33", FEATURE, "Thêm mới – Chi tiết ưu đãi", "Boundary Value",
     "Nhập Ngưỡng dừng ưu đãi = 0 → FE chặn (phải là số dương)",
     'Bảng Mô tả trường, Ngưỡng dừng ưu đãi – *"Nhập số dương"*'),

    ("SC-34", FEATURE, "Thêm mới – Chi tiết ưu đãi", "Business Logic",
     "On/Off toggle Ưu đãi theo tỷ lệ → Hệ thống tự động reset (clear) toàn bộ giá trị đã nhập trước đó của loại ưu đãi còn lại",
     'Mục "Chi tiết ưu đãi" – *"Khi người dùng On/Off toggle, hệ thống tự động reset toàn bộ Giá trị ưu đãi/ Tỷ lệ ưu đãi đã nhập trước đó [...]"*'),
    ("SC-35", FEATURE, "Thêm mới – Chi tiết ưu đãi", "Business Logic",
     "Khi KH đạt Ngưỡng dừng ưu đãi → Dừng áp dụng ngay tại giao dịch vượt ngưỡng dù CTƯĐ còn hiệu lực",
     'Mục "Chi tiết ưu đãi" – *"nếu Trường giá trị kiểm tra vượt quá ngưỡng này thì sẽ dừng áp dụng cho khách hàng ngay tại giao dịch vượt ngưỡng [...]"*'),
    ("SC-36", FEATURE, "Thêm mới – Chi tiết ưu đãi", "Business Logic",
     "Trường giá trị kiểm tra = 'Số lần ưu đãi': Hệ thống cộng lũy kế số lần giao dịch đã hưởng ưu đãi để so sánh với Ngưỡng dừng",
     'Mục "Chi tiết ưu đãi" – *"Hệ thống có cơ chế cập nhật/cộng lũy kế từ những giao dịch [...] để so sánh với ngưỡng dừng ưu đãi"*'),
    ("SC-37", FEATURE, "Thêm mới – Chi tiết ưu đãi", "Business Logic",
     "Trường giá trị kiểm tra = 'Số tiền giao dịch': Hệ thống cộng lũy kế số tiền giao dịch thỏa mãn để so sánh với Ngưỡng dừng",
     'Mục "Chi tiết ưu đãi" – *"cho phép chọn \"Số lần ưu đãi\" hoặc \"Số tiền giao dịch\" để xác định [...] ngưỡng chặn"*'),
    ("SC-38", FEATURE, "Thêm mới – Chi tiết ưu đãi", "Business Logic",
     "Không có danh sách KH cụ thể → Hệ thống đánh giá real-time tại thời điểm phát sinh giao dịch để áp dụng ưu đãi (tham chiếu US33)",
     'QA-01.7, BA – *"BA xác nhận trường hợp không có DS KH áp dụng thì sẽ đánh giá real time (Mô tả chi tiết trong US33)"*'),
    ("SC-39", FEATURE, "Thêm mới – Chi tiết ưu đãi", "Business Logic",
     "Loại tiền tệ tại CTƯĐ khác Loại tiền tệ của Code phí → Hệ thống quy đổi giá trị sang Loại tiền tệ của Code phí khi tính toán",
     'Mục "Chi tiết ưu đãi" – *"nếu Loại tiền tệ tại CTƯĐ khác Loại tiền tệ của Code phí [...] hệ thống cần phải quy đổi"*'),

    ("SC-40", FEATURE, "Thêm mới – Chi tiết ưu đãi", "UI/UX & Field Validation",
     "Toggle Ưu đãi tỷ lệ mặc định = On. Hiển thị trên cả 2 chế độ (Liên tục và Theo chu kỳ)",
     'Bảng Mô tả trường – *"Hệ thống mặc định hiển thị nếu toggle Ưu đãi theo tỷ lệ = On"*'),
    ("SC-41", FEATURE, "Thêm mới – Chi tiết ưu đãi", "UI/UX & Field Validation",
     "Loại tiền tệ: Dropdown cho từng bản ghi Chi tiết ưu đãi, chọn 1 loại tiền tệ",
     'Bảng Mô tả trường, Loại tiền tệ – *"Hiển thị danh sách và chọn 1 loại tiền tệ cho từng bản ghi Chi tiết ưu đãi"*'),
    ("SC-42", FEATURE, "Thêm mới – Chi tiết ưu đãi", "UI/UX & Field Validation",
     "SPDV: Combobox hiển thị danh sách SPDV có trạng thái = Hoạt động, hỗ trợ Search bar tìm kiếm gần đúng theo mã/tên",
     'Bảng Mô tả trường, SPDV – *"Hiển thị danh sách các SPDV có trạng thái hoạt động = Hoạt động [...] Search bar tìm kiếm nhanh"*'),
    ("SC-43", FEATURE, "Thêm mới – Chi tiết ưu đãi", "UI/UX & Field Validation",
     "Không có nút Tải lên (Upload) và Tải xuống (Download) tại phân vùng Chi tiết ưu đãi (khác US12)",
     'QA-04.1/04.2, BA – *"BA xác nhận không có tải lên, tải xuống"*'),

    # ========== MODULE: THÊM MỚI – XÁC NHẬN & PHÊ DUYỆT ==========
    ("SC-44", FEATURE, "Thêm mới – Xác nhận & Phê duyệt", "Happy Path",
     "Khai báo đầy đủ → Nhấn Xác nhận → BE validate thành công → Lưu bản ghi Chờ duyệt → Toast thành công → Hiển thị tại Tác vụ chờ duyệt",
     'Lưu đồ Bước 10.a – *"Lưu dữ liệu bản ghi CTƯĐ vừa khai báo và Hiển thị tác vụ tại màn hình Tác vụ chờ duyệt"*'),
    ("SC-45", FEATURE, "Thêm mới – Xác nhận & Phê duyệt", "UI/UX & Field Validation",
     "Nhấn Đóng tại màn hình Thêm mới → Hệ thống không lưu, quay về màn hình Quản lý CTƯĐ [QTC-15]",
     'Lưu đồ Bước 9.1/9.2 – *"Chọn Đóng → Hiển thị màn hình Chương trình ưu đãi"* [QTC-15]'),

    # ========== MODULE: STATE TRANSITION ==========
    ("SC-46", FEATURE, "State Transition", "Business Logic",
     "Trạng thái CTƯĐ = Chưa hiệu lực khi Ngày hệ thống < Ngày hiệu lực (sau Last Checker duyệt)",
     'Tham chiếu US12 – Logic chuyển trạng thái hoạt động CTƯĐ'),
    ("SC-47", FEATURE, "State Transition", "Business Logic",
     "Trạng thái CTƯĐ tự chuyển = Đang hiệu lực khi Ngày hiệu lực <= Ngày hệ thống <= Ngày hết hiệu lực",
     'Tham chiếu US12 – Logic chuyển trạng thái hoạt động CTƯĐ'),
    ("SC-48", FEATURE, "State Transition", "Business Logic",
     "Trạng thái CTƯĐ tự chuyển = Hết hiệu lực khi Ngày hệ thống > Ngày hết hiệu lực",
     'Tham chiếu US12 – Logic chuyển trạng thái hoạt động CTƯĐ'),

    # ========== MODULE: CHỈNH SỬA CTƯĐ ==========
    ("SC-49", FEATURE, "Chỉnh sửa CTƯĐ", "Happy Path",
     "Chỉnh sửa CTƯĐ trạng thái Chưa hiệu lực → Cho phép sửa toàn bộ trừ Mã CTƯĐ và Tên viết tắt → Xác nhận → Chờ duyệt",
     'Mục "Chỉnh sửa CTƯĐ" – *"Nếu trạng thái hoạt động CTƯĐ = Chưa hiệu lực, hệ thống cho phép chỉnh sửa toàn bộ [...] trừ mã CTƯĐ và trường Tên viết tắt"*'),
    ("SC-50", FEATURE, "Chỉnh sửa CTƯĐ", "Happy Path",
     "Chỉnh sửa CTƯĐ trạng thái Đang hiệu lực → Chỉ cho sửa Ngày HHL CTƯĐ (>= Ngày hệ thống) và Thêm mới bản ghi Chi tiết ưu đãi → Xác nhận → Chờ duyệt",
     'Mục "Chỉnh sửa CTƯĐ" – *"Nếu trạng thái hoạt động CTƯĐ = Đang hiệu lực, hệ thống chỉ cho phép chỉnh sửa [...] Ngày hết hiệu lực [...] Thêm mới một hoặc nhiều bản ghi [...]"*'),
    ("SC-51", FEATURE, "Chỉnh sửa CTƯĐ", "Negative Path",
     "Chỉnh sửa CTƯĐ trạng thái Hết hiệu lực → Hệ thống thông báo lỗi 'Trạng thái hoạt động của CTƯĐ không hợp lệ'",
     'Mục "Chỉnh sửa CTƯĐ" – *"Nếu trạng thái hoạt động CTƯĐ = Hết hiệu lực, hệ thống thông báo lỗi Trạng thái hoạt động của CTƯĐ không hợp lệ"*'),
    ("SC-52", FEATURE, "Chỉnh sửa CTƯĐ", "Negative Path",
     "Chỉnh sửa CTƯĐ đang có Tác vụ Chỉnh sửa ở trạng thái Chờ duyệt → Hệ thống chặn, không cho phép chỉnh sửa",
     'QA-01.5, BA – *"BA đã bổ sung yêu cầu [...] validate khi người dùng nhấn chỉnh sửa thì CTUD đó phải không tồn tại tác vụ chỉnh sửa chờ duyệt"*'),
    ("SC-53", FEATURE, "Chỉnh sửa CTƯĐ", "Negative Path",
     "Chỉnh sửa CTƯĐ Đang hiệu lực: sửa Ngày HHL CTƯĐ < Ngày hệ thống → FE chặn",
     'Mục "Chỉnh sửa CTƯĐ" – *"Ngày hết hiệu lực mới phải >= Ngày hệ thống"*'),
    ("SC-54", FEATURE, "Chỉnh sửa CTƯĐ", "Negative Path",
     "Chỉnh sửa CTƯĐ Đang hiệu lực: cố sửa nội dung bản ghi Chi tiết ưu đãi hiện hữu (Giá trị, Tỷ lệ, Loại tiền...) → Hệ thống không cho phép (readonly)",
     'QA-01.2, BA xác nhận – *"QA hiểu đúng: chỉ Thêm mới và Xóa, không cho sửa bản ghi hiện hữu"*. QA-02.3 BA cập nhật – *"chỉ cho phép thêm mới bản ghi"*'),
]

DATA_PART3 = [
    ("SC-55", FEATURE, "Chỉnh sửa CTƯĐ", "Business Logic",
     "CTƯĐ Đang hiệu lực bị Maker chỉnh sửa → Trạng thái Chờ duyệt → CTƯĐ bản gốc vẫn hoạt động bình thường cho đến khi Checker phê duyệt",
     'Tham chiếu US12 – Logic Chờ duyệt không ảnh hưởng bản gốc'),
    ("SC-56", FEATURE, "Chỉnh sửa CTƯĐ", "Business Logic",
     "Chỉnh sửa CTƯĐ Đang hiệu lực: Thêm mới bản ghi Chi tiết ưu đãi → Hệ thống kiểm tra ràng buộc (trùng SPDV, cha-con, overlap) tương tự Thêm mới, bỏ qua điều kiện Ngày HL bản ghi hiện hữu",
     'Mục "Chỉnh sửa CTƯĐ" – *"Hệ thống kiểm tra các điều kiện, ràng buộc [...] tương tự như khi thêm mới CTƯĐ, Bỏ qua điều kiện về Ngày hiệu lực của các bản ghi hiện hữu"*'),
    ("SC-57", FEATURE, "Chỉnh sửa CTƯĐ", "Business Logic",
     "Chỉnh sửa CTƯĐ Chưa hiệu lực: hệ thống kiểm tra ràng buộc tương tự Thêm mới (validate đầy đủ)",
     'Mục "Chỉnh sửa CTƯĐ" – *"Hệ thống kiểm tra các điều kiện và ràng buộc tương tự như khi thêm mới CTƯĐ"*'),

    # ========== MODULE: TOÀN VẸN DỮ LIỆU ==========
    ("SC-58", FEATURE, "Toàn vẹn dữ liệu", "Data Integrity",
     "SPDV bị chuyển trạng thái 'Không hoạt động' sau khi CTƯĐ đã duyệt: nếu dưới SPDV vẫn còn code phí → vẫn áp dụng ưu đãi; nếu không còn code phí → tự vô hiệu",
     'Tham chiếu US12 SC-77 – Logic xử lý SPDV Không hoạt động trong CTƯĐ đã duyệt'),
    ("SC-59", FEATURE, "Toàn vẹn dữ liệu", "Data Integrity",
     "Sau Last Checker duyệt Thêm mới → CTƯĐ hiển thị trên lưới Danh mục CTƯĐ với trạng thái hoạt động chính xác + Mã CTƯĐ được sinh theo US04",
     'QA-03.4, BA – *"BA xác nhận rule sinh mã CTUD tại US04"* [QTC-12]'),
    ("SC-60", FEATURE, "Toàn vẹn dữ liệu", "Data Integrity",
     "Chỉnh sửa CTƯĐ → Xóa tất cả bản ghi Chi tiết ưu đãi (danh sách rỗng) → Nhấn Xác nhận → FE chặn (phải ≥ 1 bản ghi)",
     'QA-03.3, BA – *"Hệ thống kiểm tra [...] tương tự như khi thêm mới CTƯĐ"* → validate ≥ 1 bản ghi'),

    # ========== MODULE: NFR ==========
    ("SC-61", FEATURE, "NFR", "NFR",
     "Spam click nút Xác nhận khi Thêm mới CTƯĐ → Hệ thống chỉ xử lý 1 request, không tạo trùng bản ghi Chờ duyệt",
     'NFR – Chống spam click [QTC-14.1]'),
    ("SC-62", FEATURE, "NFR", "NFR",
     "Spam click nút Xác nhận khi Chỉnh sửa CTƯĐ → Hệ thống chỉ xử lý 1 request",
     'NFR – Chống spam click [QTC-14.1]'),
    ("SC-63", FEATURE, "NFR", "NFR",
     "Spam click nút Phê duyệt tại Tác vụ chờ duyệt → Hệ thống chỉ xử lý 1 lần",
     'NFR – Chống spam click [QTC-12]'),
    ("SC-64", FEATURE, "NFR", "NFR",
     "Spam click nút Từ chối tại Tác vụ chờ duyệt → Hệ thống chỉ xử lý 1 lần",
     'NFR – Chống spam click [QTC-12]'),
    ("SC-65", FEATURE, "NFR", "NFR",
     "Spam click nút Xóa tại Tác vụ Pending → Hệ thống chỉ xử lý 1 lần",
     'NFR – Chống spam click [QTC-12]'),
    ("SC-66", FEATURE, "NFR", "NFR",
     "Mở màn hình Chỉnh sửa nhưng không thay đổi gì → Nhấn Xác nhận → FE disable nút hoặc cảnh báo 'Không có thay đổi để lưu' [QTC-14.1]",
     '[QTC-14.1] – *"FE disable nút Xác nhận hoặc hiển thị cảnh báo"*'),

    # ========== BỔ SUNG TỪ SO SÁNH VA ==========
    # --- Negative Path bổ sung ---
    ("SC-67", FEATURE, "Thêm mới – Thông tin chung", "Negative Path",
     "Nhập Ngày hiệu lực < Ngày hệ thống → FE chặn",
     'Tham chiếu US12 – *"Ngày hiệu lực không được nhỏ hơn Ngày hệ thống"*'),
    ("SC-68", FEATURE, "Thêm mới – Thông tin chung", "Negative Path",
     "Nhập Ngày ban hành > Ngày hệ thống (ngày tương lai) → FE chặn",
     'Tham chiếu US12 – *"Ngày ban hành không được lớn hơn Ngày hệ thống"*'),
    ("SC-69", FEATURE, "Thêm mới – Thông tin chung", "Negative Path",
     "Nhập Số văn bản(1) chứa ký tự chữ → FE chặn (chỉ cho phép ký tự số)",
     'Bảng Mô tả trường, Số văn bản(1) – *"Cho phép nhập ký tự số"*'),
    ("SC-70", FEATURE, "Thêm mới – Thông tin chung", "Negative Path",
     "Nhập Email CBNV đầu mối không kết thúc bằng @pvcombank.com.vn → FE chặn",
     'Bảng Mô tả trường, Email CBNV đầu mối – *"Validate định dạng email @pvcombank.com.vn"*'),
    ("SC-71", FEATURE, "Thêm mới – Điều kiện áp dụng", "Negative Path",
     "Nhập (Nguồn dữ liệu + Tên trường điều kiện + Operator) trùng lặp trong cùng 1 nhóm điều kiện → FE chặn",
     'Tham chiếu US12 – *"Không cho phép trùng lặp bộ (Nguồn dữ liệu, Trường điều kiện, Operator) trong cùng 1 nhóm"*'),
    ("SC-72", FEATURE, "Thêm mới – Chi tiết ưu đãi", "Negative Path",
     "Chọn SPDV có trạng thái ≠ Hoạt động → Hệ thống không hiển thị SPDV đó trong Combobox",
     'Bảng Mô tả trường, SPDV – *"Hiển thị danh sách các SPDV có trạng thái hoạt động = Hoạt động"*'),
    ("SC-73", FEATURE, "Thêm mới – Xác nhận & Phê duyệt", "Negative Path",
     "Mã CTƯĐ dự kiến sinh trùng với mã đã tồn tại trong hệ thống → BE báo lỗi, không cho lưu (tham chiếu US04)",
     'QA-03.4, BA – *"rule sinh mã CTUD tại US04"* – Edge case trùng mã'),
    ("SC-74", FEATURE, "Chỉnh sửa CTƯĐ", "Negative Path",
     "Chỉnh sửa CTƯĐ Đang hiệu lực: xóa hết toàn bộ bản ghi Chi tiết ưu đãi rồi nhấn Xác nhận → FE chặn (phải có ≥ 1 bản ghi)",
     'QA-03.3, BA – *"validate tương tự Thêm mới → ≥ 1 bản ghi"*'),

    # --- Boundary Value bổ sung ---
    ("SC-75", FEATURE, "Thêm mới – Thông tin chung", "Boundary Value",
     "Nhập Tên viết tắt đúng 10 ký tự (biên trên) → lưu thành công",
     'Bảng Mô tả trường, Tên viết tắt – *"Tối đa 10 ký tự"*'),
    ("SC-76", FEATURE, "Thêm mới – Thông tin chung", "Boundary Value",
     "Nhập Tên viết tắt = 11 ký tự (vượt biên) → FE chặn",
     'Bảng Mô tả trường, Tên viết tắt – *"Tối đa 10 ký tự"*'),
    ("SC-77", FEATURE, "Thêm mới – Thông tin chung", "Boundary Value",
     "Nhập Số văn bản đúng 20 ký tự (biên trên) → lưu thành công",
     'Bảng Mô tả trường, Số văn bản – *"Tối đa 20 ký tự"*'),
    ("SC-78", FEATURE, "Thêm mới – Chu kỳ áp dụng", "Boundary Value",
     "Nhập Ngày cụ thể = 31 (tháng không có ngày 31, VD tháng 2) → hệ thống hiểu là ngày cuối cùng của tháng",
     'Mockup image3 – *"Hàng tháng / Ngày cụ thể"* – Xử lý biên ngày'),
    ("SC-79", FEATURE, "Thêm mới – Chu kỳ áp dụng", "Boundary Value",
     "Nhập Ngày cụ thể = 0 hoặc 32 (ngoài khoảng 1-31) → FE chặn",
     'Mockup image3 – *"Hàng tháng / Ngày cụ thể"* – Biên ngoài khoảng'),

    # --- Business Logic bổ sung ---
    ("SC-80", FEATURE, "Thêm mới – Thông tin chung", "Business Logic",
     "Thay đổi Loại ưu đãi (VD: Theo KH → Theo Tài khoản) → Hệ thống tự động reset (clear) toàn bộ Điều kiện áp dụng đã khai báo",
     'Tham chiếu US12 – *"Thay đổi Loại ưu đãi → hệ thống tự động clear toàn bộ điều kiện"*'),
    ("SC-81", FEATURE, "Thêm mới – Thông tin chung", "Business Logic",
     "Chuyển Hình thức từ Theo chu kỳ sang Liên tục → Hệ thống tự động clear toàn bộ giá trị Chu kỳ áp dụng đã nhập",
     'Tham chiếu US12 – *"Chuyển Hình thức → clear Chu kỳ"*'),

    # --- UI/UX bổ sung ---
    ("SC-82", FEATURE, "Thêm mới – Thông tin chung", "UI/UX & Field Validation",
     "Đối tượng thu phí hiển thị dạng Radio Button (Khách hàng / Merchant), single-select, loại trừ lẫn nhau",
     'Mockup image2/3 – *"Đối tượng thu phí: ○ Khách hàng ◉ Merchant"*'),
    ("SC-83", FEATURE, "Thêm mới – Chi tiết ưu đãi", "UI/UX & Field Validation",
     "KHÔNG có trường CIF và Tên KH tại bảng Chi tiết ưu đãi (khác biệt so với US12 – toggle OFF)",
     'Lưu đồ Bước 5/6 – *"Không theo danh sách khách hàng"* → Không có CIF/Tên KH'),
    ("SC-84", FEATURE, "Thêm mới – Thông tin chung", "UI/UX & Field Validation",
     "Ngày ban hành có dấu bắt buộc (★) — áp dụng theo Mô tả chi tiết trường, không theo Mockup",
     'QA-04.7, BA – *"áp dụng theo Mô tả chi tiết trường"* → Ngày ban hành là trường bắt buộc'),
    ("SC-85", FEATURE, "Thêm mới – Thông tin chung", "UI/UX & Field Validation",
     "Tên viết tắt: tự động hiển thị chữ viết hoa và loại bỏ khoảng trắng khi user nhập",
     'Bảng Mô tả trường, Tên viết tắt – *"Tự động hiển thị chữ viết hoa và loại bỏ khoảng trắng"*'),

    # ========== BỔ SUNG TỪ REVIEW (qa_test_case_reviewer) ==========
    ("SC-86", FEATURE, "Thêm mới – Thông tin chung", "Happy Path",
     "Thêm mới CTƯĐ với Loại ưu đãi = Theo Giao dịch, ĐTPT = Khách hàng → Nguồn dữ liệu tại Điều kiện áp dụng cho phép chọn API Giao dịch hoặc ETL KH",
     'QA-01.1, BA – *"Trường Loại ưu đãi dùng để khai báo cấp độ chi tiết điều kiện ưu đãi và quyết định nguồn dữ liệu"*'),
    ("SC-87", FEATURE, "Thêm mới – Chu kỳ áp dụng", "Happy Path",
     "Hình thức = Theo chu kỳ, Hàng tháng → Chọn Ngày trong tháng (Ngày = Thứ Hai, Thứ Ba...; Tuần = Đầu tiên/Thứ hai/...) → Hệ thống ghi nhận",
     'Mockup image3, phân vùng "Chu kỳ áp dụng" – *"Hàng tháng / Ngày trong tháng / Ngày + Tuần"*'),
    ("SC-88", FEATURE, "Thêm mới – Thông tin chung", "Boundary Value",
     "Nhập Tên CTƯĐ = 1 ký tự (biên dưới min) → lưu thành công",
     'QTC-01.6 – *"Trường Tên tối đa 50 ký tự"* – BVA biên dưới'),
    ("SC-89", FEATURE, "Chỉnh sửa CTƯĐ", "Negative Path",
     "Chỉnh sửa CTƯĐ trạng thái Chưa hiệu lực: cố sửa trường Tên viết tắt → Hệ thống không cho phép (field readonly)",
     'Mục "Chỉnh sửa CTƯĐ" – *"cho phép chỉnh sửa toàn bộ [...] trừ mã CTƯĐ và trường Tên viết tắt"*'),
]

# Combine all data
DATA = DATA_PART1 + DATA_PART2 + DATA_PART3

# ========== DANH SÁCH SC LOẠI TRỪ THEO PHẢN HỒI BA ==========
EXCLUSIONS = [
    ("US13-QA-02.1", "BA xác nhận: Đã có Quy tắc chung về không giới hạn số lượng tối đa SPDV → Không sinh SC riêng"),
]

# ========== DANH SÁCH QA PENDING (DẠNG 8) ==========
PENDING = [
    ("US13-QA-01.4", "BA sẽ cập nhật lại tài liệu (Flowchart dùng tên không nhất quán với Text: 'Điều kiện đánh giá' vs 'Điều kiện áp dụng'). Chờ BA cập nhật Flowchart."),
]
