# Merged Q&A data for US22 - Combined AI + VA, deduplicated, QTC-checked
# Format: (id, ref, question, category, suggestion, source)

FEATURE = "US22 – Đăng xuất hệ thống"
MERGED_FILE = "US22_PartB_QA_Merged.docx"
OUTPUT_DIR = "/Users/mac/antigravity-testing-kit/Feature_02_SA_Tham_So_He_Thong"

QA_MERGED = [
    # --- HM1: Nghiệp vụ ---
    ("US22-QA-01.1",
     "Mục \"Yêu cầu nghiệp vụ\" – \"Chi tiết về luồng Đăng nhập, xem tại US22 – Là người dùng, tôi muốn đăng nhập vào hệ thống\"",
     "Tham chiếu sai US: Đoạn text dẫn \"xem tại US22\" nhưng US22 chính là tính năng Đăng xuất này. Đúng ra phải tham chiếu đến US21 (Đăng nhập). Đây là lỗi copy-paste.",
     "Nghiệp vụ",
     "Đề xuất: Sửa thành \"xem tại US21 – Là người dùng, tôi muốn đăng nhập vào hệ thống\".",
     "AI+VA"),
    ("US22-QA-01.2",
     "Mục \"Yêu cầu nghiệp vụ\" – \"Các tác vụ đang thực hiện (chưa hoàn tất) sẽ không được lưu khi người dùng Đăng xuất\"",
     "Tài liệu không phân biệt giữa đăng xuất thủ công (user chủ động) và tự động đăng xuất (timeout/bị kick). Cả 2 trường hợp đều không lưu tác vụ dở dang? Hay trường hợp tự động đăng xuất cần cơ chế auto-save draft?",
     "Nghiệp vụ",
     "Đề xuất: BA xác nhận cả 2 trường hợp đều KHÔNG lưu tác vụ dở dang. Không có cơ chế auto-save.",
     "VA"),
    ("US22-QA-01.3",
     "Mục \"Yêu cầu nghiệp vụ\", \"Tự động đăng xuất\" – \"Khi người dùng đăng nhập một phiên làm việc mới [...] hệ thống tự động đăng xuất phiên làm việc cũ\"",
     "Popup tự động đăng xuất hiển thị cùng nội dung cho cả 2 trường hợp: timeout và bị kick bởi phiên mới. User không phân biệt được lý do. Có cần 2 thông báo riêng biệt không?",
     "Nghiệp vụ",
     "Đề xuất: Phân biệt: (1) Timeout → \"Phiên đã hết hạn do không thao tác\" (2) Bị kick → \"Tài khoản đã đăng nhập từ thiết bị khác\". Hoặc BA xác nhận dùng chung.",
     "VA"),
    ("US22-QA-01.4",
     "Flowchart \"Đăng xuất\", Bước 5 – \"Nhận yêu cầu và xử lý đăng xuất\" (Backend)",
     "Flowchart Bước 5 (BE xử lý) đi thẳng sang Bước 6 (kết thúc phiên) mà KHÔNG có nhánh xử lý khi BE lỗi. Nếu API đăng xuất timeout/server không phản hồi → FE xử lý thế nào?",
     "Nghiệp vụ",
     "Đề xuất: Nếu BE không phản hồi, FE vẫn xóa session local (token, cookie) và redirect về Đăng nhập. BE tự invalidate session khi hết hạn.",
     "VA"),
    ("US22-QA-01.5",
     "Mục \"Lưu đồ\" – Flowchart chỉ vẽ luồng Đăng xuất thủ công (7 bước, 3 swimlane User/Frontend/Backend)",
     "Flowchart thiếu hoàn toàn luồng Tự động đăng xuất (session timeout và đăng nhập phiên mới) trong khi text mô tả rõ 2 cơ chế.",
     "Nghiệp vụ",
     "Đề xuất: Bổ sung Flowchart cho luồng Tự động đăng xuất, hoặc xác nhận chỉ cần Flowchart cho luồng thủ công.",
     "AI"),
    ("US22-QA-01.6",
     "Mục \"Yêu cầu nghiệp vụ\", \"Tự động đăng xuất\" – \"hiển thị popup [...] Người dùng chọn button Đăng nhập\"",
     "Popup tự động đăng xuất chỉ mô tả nút \"Đăng nhập\". Nếu user nhấn X (đóng popup) → phiên đã hết hạn nên không thể quay lại. Hành vi hệ thống là gì?",
     "Nghiệp vụ",
     "Đề xuất: Popup không có nút X (force chọn \"Đăng nhập\"), hoặc nhấn X cũng redirect về Đăng nhập.",
     "AI"),
    # --- HM2: Giới hạn ---
    ("US22-QA-02.1",
     "Mục \"Yêu cầu nghiệp vụ\" – \"tham số cấp hệ thống SESSION_TIMEOUT\"",
     "SESSION_TIMEOUT: Giá trị mặc định là bao nhiêu? Đơn vị (phút/giây)? Phạm vi hợp lệ? Tham số được cấu hình ở US nào?",
     "Giới hạn",
     "Đề xuất: Cần xác nhận giá trị mặc định (VD: 30 phút), đơn vị, và US quản lý tham số này.",
     "AI"),
    ("US22-QA-02.2",
     "Mục \"Yêu cầu nghiệp vụ\" – \"người dùng không có thao tác sau một khoảng thời gian\"",
     "Định nghĩa \"không có thao tác\" (idle) chưa rõ: click/keystroke/chuyển trang có tính, vậy mouse move, scroll có tính không? Hệ thống có hiển thị countdown cảnh báo trước auto-logout không?",
     "Giới hạn",
     "Đề xuất: (1) Xác nhận \"thao tác\" = click/nhập text/chuyển trang. (2) Có/không countdown cảnh báo trước auto-logout.",
     "AI+VA"),
    ("US22-QA-02.3",
     "Mục \"Yêu cầu nghiệp vụ\" – \"đăng nhập một phiên làm việc mới [...] phiên làm việc hiện tại sẽ kết thúc\"",
     "Nếu user có N phiên đang mở (nhiều tab/thiết bị) → đăng nhập phiên mới → tất cả N phiên cũ đều bị đăng xuất hay chỉ phiên cũ nhất?",
     "Giới hạn",
     "Đề xuất: Xác nhận chính sách single-session (chỉ 1 phiên duy nhất) hay cho phép N phiên đồng thời.",
     "AI"),
    # --- HM3: Toàn vẹn dữ liệu ---
    ("US22-QA-03.1",
     "Mục \"Yêu cầu nghiệp vụ\" – \"Các tác vụ đang thực hiện (chưa hoàn tất) sẽ không được lưu khi người dùng Đăng xuất\"",
     "Phạm vi \"tác vụ chưa hoàn tất\" chưa rõ: (1) Dữ liệu đang nhập trên form chưa submit → rõ ràng mất. (2) Request đã submit nhưng BE chưa xử lý xong → có bị hủy? (3) Bản ghi đã Chờ duyệt → có bị ảnh hưởng?",
     "Toàn vẹn dữ liệu",
     "Đề xuất: \"Tác vụ chưa hoàn tất\" = dữ liệu trên form chưa submit. Request đã gửi BE + bản ghi Chờ duyệt KHÔNG bị ảnh hưởng.",
     "AI+VA"),
    ("US22-QA-03.2",
     "Mục \"Yêu cầu nghiệp vụ\" – \"hệ thống đăng xuất người dùng đó khỏi phiên làm việc\"",
     "Token/session sau đăng xuất: Access token cũ có bị invalidate ngay lập tức? Nếu gọi API bằng token cũ sau đăng xuất → BE reject hay vẫn xử lý?",
     "Toàn vẹn dữ liệu",
     "Đề xuất: Token bị invalidate ngay sau đăng xuất. API call bằng token cũ phải bị reject (401).",
     "AI"),
    # --- HM4: UI/UX ---
    ("US22-QA-04.1",
     "Bảng \"Mô tả chi tiết các trường\", STT 2 \"Đồng ý\" – \"Người dùng nhấn vào button Đồn ý\"",
     "Lỗi typo: STT 2 ghi \"Đồn ý\" thiếu chữ \"g\", đúng phải là \"Đồng ý\".",
     "UI-UX",
     "Đề xuất: Sửa \"Đồn ý\" → \"Đồng ý\".",
     "AI+VA"),
    ("US22-QA-04.2",
     "Mục \"Giao diện\" – Chỉ có mockup Popup xác nhận đăng xuất thủ công",
     "Thiếu mockup popup tự động đăng xuất (\"Phiên đăng nhập hết hạn...\"). Popup này khác popup thủ công về nội dung và nút bấm.",
     "UI-UX",
     "Đề xuất: Bổ sung mockup cho popup tự động đăng xuất.",
     "AI"),
    ("US22-QA-04.3",
     "Mục \"Yêu cầu nghiệp vụ\" – \"tại thông tin user ở góc trái màn hình, người dùng chọn Đăng xuất\"",
     "Mockup image2 hiển thị nút \"Đăng xuất\" trực tiếp cạnh tên user. Nhưng Mockup image3 hiển thị user + icon 3 chấm (⋮) mà KHÔNG thấy nút Đăng xuất. Nút ẩn trong dropdown menu 3 chấm hay hiển thị trực tiếp?",
     "UI-UX",
     "Đề xuất: BA xác nhận nút Đăng xuất hiển thị trực tiếp (như image2) hay ẩn trong menu 3 chấm (như image3 gợi ý).",
     "VA"),
    ("US22-QA-04.4",
     "Mockup \"Popup Xác nhận đăng xuất\" – Popup có 2 nút \"Hủy bỏ\" và \"Đồng ý\"",
     "Click vào vùng overlay tối bên ngoài popup xác nhận đăng xuất → hành vi giống \"Hủy bỏ\" (đóng popup, không đăng xuất) hay không phản hồi? (Lưu ý: Hành vi nhấn X đã được QTC-15 quy định = đóng popup, không lưu.)",
     "UI-UX",
     "Đề xuất: Click overlay → đóng popup, không đăng xuất (tương tự QTC-15).",
     "VA (sửa theo QTC-15)"),
]
