# US38 Part B Merged Data - HM1 (References fixed with verbatim quotes)
QA_DATA = [
    ("US38-QA-01.1",
     'Mục "Yêu cầu nghiệp vụ" – *"T24 sẽ gọi API để yêu cầu ProfiX tính phí cho kỳ thu phí đầu tiên tương tự như trường hợp hạch toán thu phí kèm theo giao dịch gốc được mô tả tại US34"*',
     "Trong trường hợp T24 gọi API ProfiX lần đầu khi phát hành bảo lãnh, ProfiX cần những thông tin đầu vào gì từ T24? API spec (request/response) cho lần call này có giống hoàn toàn với API tính phí kênh quầy tại US34 không?",
     "Nghiệp vụ",
     "Đề xuất: BA/SA cần xác nhận API spec cho lần call đầu tiên: danh sách tham số đầu vào (CIF, Số MD, Giá trị bảo lãnh, Loại tiền, Sản phẩm BL...) và response (số tiền phí, mã giao dịch...).",
     "", "VA"),
    ("US38-QA-01.2",
     'Mục "Yêu cầu nghiệp vụ" – *"khoảng thời gian tính phí gửi cho ProfiX là số ngày của tháng hiện tại (ví dụ: phát hành từ ngày 07/05/2026 thì số ngày của tháng hiện tại = 31)"*',
     "Phí kỳ đầu luôn tính cho NGUYÊN THÁNG bất kể ngày phát hành nằm giữa tháng? Hay tính theo số ngày thực tế từ ngày phát hành đến cuối tháng (07/05 → 31/05 = 25 ngày)?",
     "Nghiệp vụ",
     "Đề xuất: BA làm rõ 'số ngày của tháng hiện tại' là (a) tổng số ngày lịch của tháng (31) hay (b) số ngày còn lại từ ngày phát hành.",
     "", "AI+VA"),
    ("US38-QA-01.3",
     'Mục "Yêu cầu nghiệp vụ" – *"Hằng ngày, tại thời điểm đầu ngày, ProfiX tự động kiểm tra các khoản bảo lãnh chưa xác định thời hạn đến hạn thu phí bảo lãnh định kỳ trong ngày [...]"*',
     "Ngày đến hạn kỳ thu phí tiếp theo (sau kỳ đầu) được tính thế nào? VD: Phát hành ngày 07/05 → kỳ 2 là 07/06 (cộng 1 tháng) hay 01/06 (đầu tháng)? Nếu ngày 31/01 thì tháng 2 (28 ngày) xử lý ra sao?",
     "Nghiệp vụ",
     "Đề xuất: BA cần làm rõ quy tắc tính ngày đến hạn kỳ tiếp theo với ví dụ cụ thể, bao gồm edge case tháng có số ngày khác nhau.",
     "", "VA"),
    ("US38-QA-01.4",
     'Mục "Yêu cầu nghiệp vụ" – *"Nếu khoản bảo lãnh có Thu phí phí tự động = Không, hệ thống không xử lý gì tiếp theo."*',
     "Khi Thu phí tự động = Không, hệ thống có ghi nhận kỳ phí đến hạn vào danh sách 'Chờ thu thủ công' không? Hay kỳ phí đó bị bỏ qua hoàn toàn?",
     "Nghiệp vụ",
     "Đề xuất: Bổ sung cơ chế ghi nhận kỳ phí đến hạn ở trạng thái 'Chờ thu thủ công' khi Thu phí tự động = Không.",
     "", "VA"),
    ("US38-QA-01.5",
     'Bảng "Diễn giải lưu đồ Thu phí thủ công", Bước 6 – *"Khi user maker commit giao dịch, T24 thực hiện call API đến ProfiX để lấy lại danh sách các khoản phí định kỳ đến hạn"*',
     "Tại sao T24 phải gọi API 2 lần (bước 2 và bước 6)? Trạng thái 'không hợp lệ' cụ thể là gì? VD: kỳ thu phí đã được batch job tự động thanh toán giữa lúc Maker chọn và commit?",
     "Nghiệp vụ",
     "Đề xuất: BA liệt kê các trạng thái thanh toán hợp lệ/không hợp lệ và xác nhận mục đích gọi API lần 2 (double-check race condition).",
     "", "AI+VA"),
    ("US38-QA-01.6",
     'Bảng "Diễn giải lưu đồ Thu phí thủ công", Bước 8.1 – *"T24 hiển thị thông báo lỗi khi trạng thái không hợp lệ"* (Flowchart không vẽ nhánh tiếp theo)',
     "Sau khi báo lỗi (bước 8.1), Maker có thể chọn lại kỳ khác không? Hay giao dịch bị hủy hoàn toàn? Flowchart kết thúc tại bước 8.1 mà không có mũi tên.",
     "Nghiệp vụ",
     "Đề xuất: Bổ sung nhánh sau bước 8.1: (a) Maker quay về bước 5 chọn lại kỳ, HOẶC (b) Giao dịch rollback.",
     "", "AI+VA"),
    ("US38-QA-01.7",
     'Mục "Yêu cầu nghiệp vụ", danh sách trường ETL – *"Tần suất thu phí = Tháng/Qúy"*',
     "Toàn bộ phần yêu cầu chỉ mô tả logic thu 1 tháng/lần. Nếu Tần suất = Quý: (a) Kỳ đầu tính phí bao nhiêu ngày? (b) Kỳ tiếp theo: cộng 3 tháng hay đầu quý? (c) Công thức tính số ngày?",
     "Nghiệp vụ",
     "Đề xuất: BA làm rõ logic Tần suất = Quý với ví dụ cụ thể gồm ngày đến hạn và số ngày tính phí.",
     "", "AI+VA"),
    ("US38-QA-01.8",
     'Mục "Yêu cầu nghiệp vụ" – *"dữ liệu khoản bảo lãnh sẽ được đồng bộ vào bảng ETL Tài khoản của ProfiX làm dữ liệu nguồn cho các kỳ thu phí định kỳ tiếp theo"*',
     "Bảo lãnh phát hành lúc 16:00, DWH batch ETL chạy lúc 23:00 cùng ngày, dữ liệu có mặt ProfiX vào T+1. Kỳ phí thứ 2 có được tính đúng không nếu dữ liệu nguồn chậm 1 ngày?",
     "Nghiệp vụ",
     "Đề xuất: Xác định SLA của DWH ETL (thời điểm hoàn thành đồng bộ) và ảnh hưởng đến tính phí kỳ tiếp theo.",
     "", "VA"),
    ("US38-QA-01.9",
     'Bảng "Diễn giải lưu đồ Thu phí thủ công", Bước 9 – *"User Checker phê duyệt giao dịch"* (Flowchart không vẽ nhánh từ chối)',
     "Tài liệu không mô tả luồng Checker TỪ CHỐI. Khi từ chối: (a) Giao dịch về trạng thái nào? (b) Maker chỉnh sửa lại được không? (c) Các kỳ thu phí đã chọn có bị lock?",
     "Nghiệp vụ",
     "Đề xuất: BA bổ sung luồng Checker từ chối, xác định trạng thái sau từ chối và cơ chế lock/unlock kỳ thu phí.",
     "", "AI"),
    ("US38-QA-01.10",
     'Mục "Yêu cầu nghiệp vụ" – *"tương tự như trường hợp hạch toán thu phí kèm theo giao dịch gốc được mô tả tại US34 về việc tự động tính phí trên kênh quầy/nội bộ"*',
     "Khoản bảo lãnh chưa xác định thời hạn có được phép miễn/giảm phí theo CTƯĐ không? Nếu có, CTƯĐ áp dụng kỳ đầu có hiệu lực xuyên suốt các kỳ định kỳ sau?",
     "Nghiệp vụ",
     "Đề xuất: BA xác nhận bảo lãnh chưa xác định thời hạn có nằm trong scope CTƯĐ không, và hiệu lực CTƯĐ xuyên kỳ hay chỉ kỳ đầu.",
     "", "AI"),
    ("US38-QA-01.11",
     'Bảng "Diễn giải lưu đồ Thu phí thủ công", Bước 5 – *"User Maker lựa chọn các kỳ cần thu"*',
     "Maker chọn nhiều kỳ cùng lúc. Nếu bước 8 phát hiện 1 kỳ không hợp lệ: (a) Cả batch bị rollback (all-or-nothing) hay chỉ reject kỳ lỗi (partial)? (b) Maker thấy breakdown phí từng kỳ trước commit?",
     "Nghiệp vụ",
     "Đề xuất: BA xác nhận cơ chế all-or-nothing hay partial success khi multi-select, và Maker có thấy chi tiết phí từng kỳ không.",
     "", "AI"),
]
