# US38 Part B Merged Data Part 2 - HM2, HM3, HM4 (References fixed)
QA_DATA_2 = [
    # ===== HM2 =====
    ("US38-QA-02.1",
     'Bảng "Diễn giải lưu đồ Đồng bộ dữ liệu", Bước 1 – *"Mô tả chi tiết về các bảng dữ liệu ETL sẽ được các bên thống nhất trong quá trình triển khai"*',
     "Nếu ETL từ DWH vào ProfiX gặp lỗi (DWH not available, dữ liệu corrupt), ProfiX xử lý thế nào vào đầu ngày hôm sau? Có cơ chế alert/monitoring? Có retry policy?",
     "Giới hạn",
     "Đề xuất: Định nghĩa cơ chế xử lý khi ETL thất bại: retry policy, alert cho DWH team, và hành vi ProfiX khi dữ liệu không được cập nhật.",
     "", "AI+VA"),
    ("US38-QA-02.2",
     'Mục "Yêu cầu nghiệp vụ", danh sách trường ETL – *"Có ký quỹ? = Có/Không; Tỷ lệ ký quỹ; Giá trị ký quỹ; Có TSBĐ? = Có/Không; Loại TSBĐ; Giá trị bảo đảm bằng TSBĐ; Giá trị không có TSBĐ"*',
     "Những trường này ảnh hưởng thế nào đến công thức tính phí bảo lãnh? Mức phí khác nhau tùy có/không ký quỹ hoặc loại TSBĐ? Tài liệu chưa mô tả công thức.",
     "Giới hạn",
     "Đề xuất: Bổ sung công thức tính phí bảo lãnh định kỳ sử dụng tham số ký quỹ và TSBĐ, hoặc tham chiếu rõ US nào định nghĩa công thức.",
     "", "VA"),
    ("US38-QA-02.3",
     'Mục "Yêu cầu nghiệp vụ" – *"hệ thống thực hiện giao dịch thu phí thủ công sẽ kết nối tới ProfiX để lấy danh sách các khoản phí bảo lãnh định kỳ của Khách hàng"*',
     "API lấy danh sách kỳ phí có giới hạn số bản ghi trả về không? Nếu KH có hàng trăm kỳ phí đến hạn, T24 xử lý hết không? Có phân trang?",
     "Giới hạn",
     "Đề xuất: Xác định giới hạn số bản ghi API response và cơ chế phân trang nếu vượt ngưỡng.",
     "", "VA"),
    ("US38-QA-02.4",
     'Mục "Yêu cầu nghiệp vụ", danh sách trường ETL – *"Xác định thời hạn? = Có/Không"*',
     "Bảng ETL đồng bộ cả hai loại hay chỉ loại 'Không'? Nếu khoản BL ban đầu 'Không' → sau đó KH bổ sung thời hạn → đổi thành 'Có', ProfiX có dừng theo dõi và không thu phí theo US38?",
     "Giới hạn",
     "Đề xuất: Mô tả hành vi ProfiX khi trường 'Xác định thời hạn?' chuyển từ Không → Có: dừng lịch thu phí US38, chuyển cơ chế khác, hay can thiệp thủ công.",
     "", "AI+VA"),
    ("US38-QA-02.5",
     'Bảng "Diễn giải lưu đồ Thu phí thủ công", Bước 2 – *"T24 thực hiện call API đến ProfiX để lấy danh sách các khoản phí định kỳ đến hạn"* (và Bước 6, 10)',
     "Nếu API ProfiX timeout/down ở bước 2, 6, hoặc 10, T24 xử lý thế nào? Có retry hay rollback giao dịch?",
     "Giới hạn",
     "Đề xuất: BA/SA định nghĩa timeout và cơ chế xử lý cho từng lần call API, đặc biệt bước 10.",
     "", "AI"),
    ("US38-QA-02.6",
     'Bảng "Diễn giải lưu đồ Thu phí thủ công", Bước 10 – *"T24 xử lý hạch toán, call API đến ProfiX để ghi nhận thông tin thu phí thành công"*',
     "Bước 10 gồm 2 action: hạch toán T24 + call API ProfiX. Nếu hạch toán OK nhưng API ProfiX thất bại → T24 đã trừ tiền KH nhưng ProfiX chưa ghi nhận → thu trùng kỳ sau.",
     "Giới hạn",
     "Đề xuất: BA/SA xác định cơ chế consistency: (a) T24 hạch toán SAU KHI ProfiX confirm, HOẶC (b) Có luồng compensation.",
     "", "AI"),
    ("US38-QA-02.7",
     'Mục "Yêu cầu nghiệp vụ" – *"Hằng ngày, tại thời điểm đầu ngày, ProfiX tự động kiểm tra các khoản bảo lãnh chưa xác định thời hạn đến hạn thu phí [...]"*',
     "Nếu batch job fail giữa chừng (đã xử lý 50/100 khoản), cơ chế resume/retry? Có xử lý idempotent tránh thu trùng khi retry?",
     "Giới hạn",
     "Đề xuất: Tham chiếu US35 về cơ chế retry batch. BA xác nhận batch US38 áp dụng cùng cơ chế, bao gồm idempotency check.",
     "", "AI"),
    # ===== HM3 =====
    ("US38-QA-03.1",
     'Mục "Yêu cầu nghiệp vụ" – *"thực hiện quy trình sinh dữ liệu phí bảo lãnh định kỳ đến hạn tham chiếu đến US35 về Hệ thống tự động thu các loại phí định kỳ"*',
     "Kỳ phí bảo lãnh do US38 sinh ra có quản lý trong cùng bảng dữ liệu kỳ phí với các loại phí định kỳ khác (US35) không? Hay bảo lãnh có bảng riêng?",
     "Toàn vẹn dữ liệu",
     "Đề xuất: Xác nhận cấu trúc dữ liệu: kỳ phí bảo lãnh và kỳ phí thông thường dùng chung hay bảng riêng.",
     "", "VA"),
    ("US38-QA-03.2",
     'Mục "Yêu cầu nghiệp vụ", danh sách trường ETL – *"Giá trị bảo lãnh"* – thuộc *"dữ liệu nguồn cho các kỳ thu phí định kỳ tiếp theo"*',
     "Giá trị bảo lãnh có thể thay đổi (giải tỏa một phần). Nếu thay đổi giữa 2 kỳ, ProfiX lấy giá trị nào tính phí: snapshot ETL T-1 hay giá trị tại thời điểm sinh kỳ phí?",
     "Toàn vẹn dữ liệu",
     "Đề xuất: Làm rõ snapshot policy: giá trị bảo lãnh dùng tính phí lấy tại thời điểm nào.",
     "", "AI+VA"),
    ("US38-QA-03.3",
     'Lưu đồ "Đồng bộ dữ liệu bảo lãnh và thu phí bảo lãnh định kỳ tự động", Bước 2.1 – *"Sinh phí bảo lãnh định kỳ đến hạn & thu tự động"*',
     "Flowchart không vẽ nhánh khi bước 2.1 không tìm được khoản nào đến hạn (kết quả rỗng). Hệ thống ghi log? Cảnh báo? Hay kết thúc bình thường?",
     "Toàn vẹn dữ liệu",
     "Đề xuất: Bổ sung nhánh 'Không có khoản BL đến hạn': batch kết thúc bình thường, ghi log audit.",
     "", "VA"),
    ("US38-QA-03.4",
     'Bảng "Diễn giải lưu đồ Thu phí thủ công" – Cột "Bước" có nhiều dòng trống giá trị STT (chỉ có Bước 8.1 được đánh số)',
     "Bảng TABLE 1 thiếu STT cho nhiều bước. Đây là lỗi định dạng tài liệu, cần bổ sung STT để Tester trace test case đúng bước.",
     "Toàn vẹn dữ liệu",
     "Đề xuất: Bổ sung STT đầy đủ cho tất cả bước trong bảng diễn giải để đảm bảo traceability với Flowchart.",
     "", "VA"),
    ("US38-QA-03.5",
     'Mục "Yêu cầu nghiệp vụ" – *"Các khoản phí bảo lãnh đến hạn thu chưa thành công (bao gồm cả Thu phí tự động chưa thành công) sẽ được người dùng thu thủ công [...]"*',
     "Cơ chế đánh dấu kỳ đã thu? Batch job sau đó có bỏ qua? API response cho thu thủ công trả TẤT CẢ kỳ hay chỉ 'Chưa thanh toán'? Cần filter để tránh thu trùng với US36.",
     "Toàn vẹn dữ liệu",
     "Đề xuất: ProfiX cần flag/status trên mỗi kỳ (Chưa thu/Đang thu/Đã thu/Thất bại). API response chỉ trả kỳ 'Chưa thanh toán'.",
     "", "AI+VA"),
    ("US38-QA-03.6",
     'Mục "Yêu cầu nghiệp vụ", danh sách trường ETL – *"Trạng thái tài khoản: mặc định chỉ lấy các tài khoản còn hoạt động"*',
     "Nếu khoản BL bị tất toán/đóng giữa kỳ (sau ETL T-1), batch job đầu ngày vẫn thu phí cho khoản đã đóng? Có kiểm tra trạng thái realtime trước khi thu?",
     "Toàn vẹn dữ liệu",
     "Đề xuất: BA xác nhận: (a) ProfiX chỉ dùng ETL T-1 (chấp nhận trễ 1 ngày), HOẶC (b) ProfiX check realtime.",
     "", "AI"),
    ("US38-QA-03.7",
     'Mục "Yêu cầu nghiệp vụ", danh sách trường ETL – *"Thu phí tự động = Có/Không trong đó bao gồm tham số Thu phí tự động = Có/Không"*',
     "Nếu tham số thay đổi Có → Không (hoặc ngược lại) giữa các kỳ, hệ thống áp dụng giá trị nào? Snapshot ETL T-1 hay giá trị tại thời điểm batch chạy?",
     "Toàn vẹn dữ liệu",
     "Đề xuất: BA xác nhận nguồn dữ liệu quyết định: ETL snapshot T-1 hay call realtime.",
     "", "AI"),
    # ===== HM4 =====
    ("US38-QA-04.1",
     'Mục "Giao diện" / "Màn hình" – *"N/A"* và Mục "Mô tả chi tiết các trường" – *"N/A"*',
     "US38 ghi Giao diện = N/A. Luồng thu thủ công trên T24. ProfiX team chỉ test API response? Có màn hình ProfiX xem kỳ phí BL đến hạn/lịch sử thu phí không?",
     "UI-UX",
     "Đề xuất: BA xác nhận phạm vi test ProfiX: chỉ API (cần API spec chi tiết) hay bao gồm cả giao diện T24.",
     "", "AI+VA"),
    ("US38-QA-04.2",
     'Bảng "Diễn giải lưu đồ Thu phí thủ công", Bước 4 – *"T24 hiển thị danh sách các kỳ thu phí bảo lãnh định kỳ đến hạn"*',
     "Danh sách kỳ thu phí gồm những thông tin gì? (Số MD, Ngày đến hạn, Số tiền phí, Trạng thái, Loại tiền...). Tài liệu không mô tả cấu trúc API response.",
     "UI-UX",
     "Đề xuất: BA/SA bổ sung API specification: request parameters và response fields.",
     "", "AI+VA"),
    ("US38-QA-04.3",
     'Mục "Yêu cầu nghiệp vụ", danh sách trường ETL – *"Loại TSBĐ = Tiền gửi PVCB/Tiền gửi khác/Tài sản khác"*',
     "Tài liệu mô tả đây là dữ liệu nguồn tính phí nhưng không có màn hình hiển thị. Trên Lịch sử thu phí hay báo cáo, Loại TSBĐ có được hiển thị?",
     "UI-UX",
     "Đề xuất: Xác nhận Loại TSBĐ có hiển thị trên Lịch sử thu phí hay báo cáo để phục vụ đối chiếu.",
     "", "VA"),
]
